### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by newswim** [lijinke666/react-music-player#10]
This function `autdioSeeked` appears several times in codebase. I think it should be `audioSeeked` (without the additional 't').

**Comment by lijinke666** [comment]
@newswim Thank you for you feedback,  You are a careful person 👍 , I will revise it

**Comment by newswim** [comment]
😸 
Thank you! Great work :)

**Comment by lijinke666** [comment]
@newswim hello! The problem has already been settled  , pelease see `version@3.2.1` thanks again
