### ISSUE TITLE
Is there a way to show the full view (at bottom of screen) on mobile?

### ISSUE THREAD

**Issue by JeffreyCA** [lijinke666/react-music-player#100]
I think it's similar to the request in https://github.com/lijinke666/react-music-player/issues/30

How can I show the regular full view on a mobiel device?

**Comment by lijinke666** [comment]
Sound great.  i will add a option to support the feature

**Comment by lijinke666** [comment]
Fixed. thank your feedback. please upgrade 4.12.0

```js
<ReactJkMusicPlayer responsive={false} />
```

**Comment by NISHANT061** [comment]
reponsive ={false} doesn't work properly.
Here is my implementation :
 ```
 <ReactJkMusicPlayer
                  {...options}
                  responsive={false}
                  className="CustomReactJinke"
                  autoPlay={true}
                  remember={false}
                  glassBg={true}
                  showDownload={false}
                  showMiniProcessBar={true}
                  showPlayMode={false}
                  showDestroy={true}
/>
```
but this doesn't work .When toggled to mobile screen using developer tool,mobile version of player is showing.
