### ISSUE TITLE
Dark theme always loaded even if set to light

### ISSUE THREAD

**Issue by JeffreyCA** [lijinke666/react-music-player#101]
### Version
4.11.2

### Description
I have the component setup like the following:
```js
import ReactJkMusicPlayer from 'react-jinke-music-player';
import 'react-jinke-music-player/assets/index.css';

<ReactJkMusicPlayer
        audioLists={[]}
        mode="full"
        toggleMode={false}
        drag={false}
        remove={false}
        theme="light"
        autoHiddenCover={true}
        showDownload={false} showPlayMode={false} showReload={false} showThemeSwitch={false} showLyric={false}  />
```

However the music player is still using the dark theme.

I digged a bit further and it looks like the `<div class="react-jinke-music-player-main">` element does not have `light-theme` or `dark-theme` as a class.

**Comment by lijinke666** [comment]
Fixed. thank your feedback. please upgrade `4.12.0`
