### ISSUE TITLE
演示demo的播放器拖动有问题

### ISSUE THREAD

**Issue by patience00** [lijinke666/react-music-player#113]
### Steps
鼠标拖动播放器后,释放左键,播放器依然会跟着鼠标跑
```js
/**
 * code
 */


```

**Comment by lijinke666** [comment]
好的 谢谢反馈 下班有空看一下

**Comment by lijinke666** [comment]
感谢反馈, 是一个bug, 因为播放器迷你模式 既要支持 拖拽, 又要支持 打开详情面板, 所以需要判断拖动坐标偏移量, 两三年前写的这段逻辑, 一直没注意, 最新版本已修复。
