### ISSUE TITLE
clearPriorAudioLists

### ISSUE THREAD

**Issue by steveambielli** [lijinke666/react-music-player#115]
### Version
4.13.1

### Description
When setting the boolean to true and updating the audioLists via setState, I get this error:

TypeError: Cannot read property 'id' of undefined
ReactJkMusicPlayer.getPlayId
C:/[PATH]/node_modules/react-jinke-music-player/es/index.js:1052
```
  1049 | _defineProperty(_assertThisInitialized(_this), "getPlayId", function () {
  1050 |   var audioLists = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : _this.state.audioLists;
  1051 |   var playIndex = Math.max(0, Math.min(audioLists.length, _this.props.defaultPlayIndex));
  1052 |   var playId = _this.state.playId || audioLists[playIndex].id;
       | ^  1053 |   return playId;
  1054 | });
  1055 | 
```

### Expected Behavior
The audioList should be cleared out and the new state should be loaded.

**Comment by lijinke666** [comment]
Can you show your code ? your `audioLists` is empty array after updated? 
```js
console.log(your audio lists)
```

**Comment by steveambielli** [comment]
When the app loads the `playlist` state is empty:

`this.state {
   playlist: ''
}`

In `componentDidMount()` it calls the function `this.getPlaylist()` and passes a variable for the playlist to fetch which changes the state of `playlist`. This is where the error is thrown and this morning it's throwing two errors.

`TypeError: Cannot read property 'id' of undefined`

`
1049 | _defineProperty(_assertThisInitialized(_this), "getPlayId", function () {
1050 |   var audioLists = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : _this.state.audioLists;
1051 |   var playIndex = Math.max(0, Math.min(audioLists.length, _this.props.defaultPlayIndex));
1052 |   var playId = _this.state.playId || audioLists[playIndex].id;
1053 |   return playId;
1054 | });
`
and
`
TypeError: Cannot read property 'stop' of undefined
  1951 |     this.unBindKeyDownEvents();
  1952 |     this.media.removeListener(this.listenerIsMobile);
  1953 |     this.media = undefined;
> 1954 |     this.lyric.stop();
 | ^  1955 |   }
  1956 | }, {
  1957 |   key: "componentDidMount",
`

**Comment by lijinke666** [comment]
> TypeError: Cannot read property 'stop' of undefined

https://github.com/lijinke666/react-music-player/blob/master/src/index.js#L1923

beasuse player only init when playlist not empty in `componentDidMount`, so `this.lyric` not be init. it's a bug. i will to fix it. sry.

> TypeError: Cannot read property 'id' of undefined

please upgrade latest version `4.14.0`, i think the issue is fixed.

 it's a  temporary solution

```diff
- this.state = { playlist: '' }
+ this.state = { playlist: [{}] }
```

thank your feedback.

**Comment by lijinke666** [comment]
fixed.
