### ISSUE TITLE
How to play next and previous song by API?

### ISSUE THREAD

**Issue by Jedliu** [lijinke666/react-music-player#117]
### How to play next and previous song by API?

Thanks for making such a great player!

Currently, we could call Play/Pause/Reload/Change Current Play Time and etc on Custom UI. Would it be possible to call PlayNext, PlayPrevious, and ChangePlayMode (loop, repeat, shuffle) as well? I tried to do it by updating the playIndex. However, it works not correctly.

Thank you,

**Comment by lijinke666** [comment]
>  I tried to do it by updating the playIndex. However, it works not correctly.

please provide a online url , what's your download player version?

**Comment by lijinke666** [comment]
[![Edit cold-shadow-w7lzs](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cold-shadow-w7lzs?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Jedliu** [comment]
Thank you. This is very helpful! 

How about the change playMode? I tried to update the parameter of 'defaultPlayMode' but it doesn't work.

**Comment by lijinke666** [comment]
not currently supported by playMode, welcome pr

**Comment by Jedliu** [comment]
Thank you for your reply. I will look into this again.

**Comment by lijinke666** [comment]
4.14.2 support change playMode now.

```
<ReactJkMusicPlayer playMode={...} />
```

**Comment by Jedliu** [comment]
Wow, that's great! Thank you!

**Comment by lijinke666** [comment]
Ok. please open a new issue. thanks
