### ISSUE TITLE
onAudioProgress handler problem

### ISSUE THREAD

**Issue by Jedliu** [lijinke666/react-music-player#119]
Please check this [**Codesandbox**](https://codesandbox.io/s/strange-on-audio-progress-mp6pz)

As soon as you add the onAudioProgress handler and access the duration and currentTime properties. You will not be able to play the next or previous song but the current song is repeated again and again. No matter you press the next or previous button or click another song in the playlist, it remains the same.

Kindly check it. Thank you,

_Originally posted by @Jedliu in https://github.com/lijinke666/react-music-player/issues/117#issuecomment-641986867_

**Comment by Jedliu** [comment]
However, if you change the playIndex, it works normally.

Thank you,

**Comment by lijinke666** [comment]
Thank your feedback fixed (v.4.15.0).

[![Edit strange-on-audio-progress](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-on-audio-progress-ypji5?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Jedliu** [comment]
It works like a charm! Thank you!
