### ISSUE TITLE
Noob Question: Delete song in AudioPanel doesnt update audioLists

### ISSUE THREAD

**Issue by Derrick-Aung** [lijinke666/react-music-player#121]
### Version
4.14.2

### Description
Using the Remove song/delete audio lists button in the AudioPanel does not delete the respective song in my state although it disappears in the UI. How would I go about solving this so that the changes are reflected in the state as well?

**Comment by K1llMan** [comment]
Same thing. Is there any handlers for removing track from queue and clear all queue?

**Comment by lijinke666** [comment]
You should study [controlled-components](https://reactjs.org/docs/forms.html#controlled-components)

this is online example. hope useful for you.

[![Edit controlled-audiolists](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/controlled-audiolists-w0vor?fontsize=14&hidenavigation=1&theme=dark)

**Comment by chaos87** [comment]
Hi @lijinke666,

Sorry for asking help on this one. Your CodeSandbox was useful to me few months ago. I noticed a bug though. When you click on the trash icon, it does not immediately clear the audio panel. You have to click twice for the audio panel to be cleared. Why is it behaving like that? 

Thanks!
