### ISSUE TITLE
Keyboard is completely locked when player is active

### ISSUE THREAD

**Issue by msveshnikov** [lijinke666/react-music-player#122]
You cannot type in any React-controlled input.
Even F12 in Chrome is not working.

**Comment by baj84** [comment]
Yeah second this. I'm using material-ui and all my inputs are made readonly. Unsure if there is a work around for this?

**Comment by lijinke666** [comment]
fixed.

**Comment by baj84** [comment]
Thanks for fixing it so quickly!
