### ISSUE TITLE
TypeError: Cannot set property 'currentTime' of null

### ISSUE THREAD

**Issue by chaos87** [lijinke666/react-music-player#123]
Hi, thanks a lot for this library!

### Version
4.15.3
### Description
Exception is thrown and screen turns blank when deleting last song in playlist (if song is playing).

### Steps to Reproduce
Can reproduce using demo https://www.lijinke.cn/react-music-player/
Start playing one of the playlist then open the playlist and click the cross icon next to each song to remove them one by one.

### Expected Behavior
Same as clearing playlist (trash icon)

### Current Behavior
Blank screen and sends exception

**Comment by lijinke666** [comment]
fixed.
