### ISSUE TITLE
OnPlayNext eventhandler

### ISSUE THREAD

**Issue by shaogu** [lijinke666/react-music-player#129]
### Description
Is it possible to handle the event when I click the ">|" icon (Something like onPlayNext((e) => ...))? I know I can do a custom UI to make it possible, but I prefer the given UI so that I can make the audio player persistant

**Comment by lijinke666** [comment]
I don't kown why you want custom to handle onPlayerNext event, what is your usage scenario?

**Comment by shaogu** [comment]
Hi, 
I am trying to develop a music room which users can join the room and listen to music together. I know I can use onPlayIndexChange as an alternative to onPlayNext. One part of my project is when the playIndex change, one user can "broadcast" the current playIndex to all the other users in the room so that they can also update the current playIndex. However, onPlayIndexChange will cause infinite loop after "broadcasting" because the playindex somehow keeps switching itself in an infinite state. So my first thought is to open an issue to ask if there is a PlayNextHandler which is more likely to solve my problem. Even though there may be other ways to do it, I just want to try to ask here to see if there is any solution.

Thanks in advance

**Comment by lijinke666** [comment]
you can try use `onAudioPlayTrackChange`

https://github.com/lijinke666/react-music-player/blob/019579951ef8c192e774948b5e2832653265f3d3/example/example.js#L281

you can get `playIndex` from audioInfo

**Comment by shaogu** [comment]
Thanks. That helps a lot
