### ISSUE TITLE
Is there a way i can stream the audio?

### ISSUE THREAD

**Issue by himanshu31shr** [lijinke666/react-music-player#13]
It doesn't seem to stream the audio, rather it does download the whole file first making it quite slow.

**Comment by lijinke666** [comment]
@himanshu31shr  Hi~  The component current version use `<audio preload="auto"/>` ,  so  download the entire file as a result of initialization.  that's so bad . i think should be remove `preload` attribute
I'm try use `Web Audio Api` suport stream , and download section in the next version .

**Comment by himanshu31shr** [comment]
Sounds great! For now i managed to build api for streaming audio using node fs. Is there any other way around you know?
