### ISSUE TITLE
Failed to construct 'MediaMetadata': required member src is undefined.

### ISSUE THREAD

**Issue by chaos87** [lijinke666/react-music-player#130]
### Version
4.16.1

### Description
When showMediaSession = true, it is not possible to skip tracks in your playlist with the fast forward button.

### Steps to Reproduce
I couldn't reproduce it using the demo website as I don't see an option to set showMediaSession to true.

### Expected Behavior
Same behavior as when showMediaSession = false; user can skip tracks however he wishes.

### Current Behavior
Getting Uncaught Error (in the console)

Uncaught TypeError: Failed to construct 'MediaMetadata': required member src is undefined.
    at n.updateMediaSessionMetadata (index.js:1487)
    at n.<anonymous> (index.js:335)
    at da (react-dom.production.min.js:131)
    at al (react-dom.production.min.js:212)
    at pu (react-dom.production.min.js:255)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vo (react-dom.production.min.js:122)
    at du (react-dom.production.min.js:248)
    at Zl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123

Again thanks for the awesome work and your patience!
Let me know if you need more info

**Comment by lijinke666** [comment]
can your show me your code ?

**Comment by chaos87** [comment]
Here you go https://github.com/chaos87/backtube/blob/master/src/App.js
Thanks for the help, I just started learning React a month ago

**Comment by lijinke666** [comment]
you website It looks good, thanks for using the player. i'think this is a bug

https://github.com/lijinke666/react-music-player/blob/d037b4351c67f1d3e023f80936d988489ea6f10d/src/index.js#L1893-L1907

i forget compatible with no cover case

in the your app only have  `name` and `musicSrc` field. so `MediaMetadata ` throw error

https://github.com/chaos87/backtube/blob/221f802a8f89a45bf3e18df09e5648e9ab5ebe50/src/App.js#L92-L96

thank your feedback, I will fix it as soon as possible

**Comment by chaos87** [comment]
Thanks for the feedback! 

Well spotted, I just set autoHiddenCover back to false and assign the image as shown on the card as cover and it works!

**Comment by lijinke666** [comment]
fixed.
