### ISSUE TITLE
Pages scroll down when audioList is modified

### ISSUE THREAD

**Issue by olivort** [lijinke666/react-music-player#133]
Hello,

On the demo page, and on my app, the page scroll down to the player when a track is added to the audioList by onAddAudio (full player in the footer).
Is there a way to disable this behaviour?

thanks

**Comment by lijinke666** [comment]
Hi~
I'm sorry to reply you so late. I will fix this problem as soon as possible

**Comment by lijinke666** [comment]
@olivort fixed.
