### ISSUE TITLE
Stream audio sending custom headers to server

### ISSUE THREAD

**Issue by jcvegan** [lijinke666/react-music-player#134]
Is there a way to control the request info you send to the server?

Meaning, sent a jwtoken or a subscription key?

**Comment by lijinke666** [comment]
I think the player only receive music src, the player can't do it, and shouldn't do it, maybe you can use `service worker` to  intercept current http request. https://stackoverflow.com/questions/9299189/send-custom-http-request-header-with-html5-audio-tag
