### ISSUE TITLE
Responsive prop doesn't work

### ISSUE THREAD

**Issue by NISHANT061** [lijinke666/react-music-player#136]
Repsonsive prop that is responsive={false} does't work .

**Comment by lijinke666** [comment]
Need reproduce steps or online link, please input question by issue template, how do I troubleshoot problems without any information?

**Comment by NISHANT061** [comment]
The site is not live > I am adding a scrrenshot here .I have use responsive={false} in props to the player but it doesn't work.
![screencapture-localhost-3007-episodes-smackdown-review-4th-jan-2020-2020-08-02-00_06_10](https://user-images.githubusercontent.com/31414953/89108215-3fbe5100-d454-11ea-830b-ab484e2d8e63.png)

**Comment by lijinke666** [comment]
Cannot reproduce. please confirm your player version
![image](https://user-images.githubusercontent.com/21015895/89263140-48d13d00-d663-11ea-8877-8275f265e139.png)
