### ISSUE TITLE
Who is using the player ? 👬

### ISSUE THREAD

**Issue by lijinke666** [lijinke666/react-music-player#137]
if you or your organization is using `react-jinke-music-player`, welcome comment.
🍻  Recommended reply format:

```
- Product：
- Company or Organization: (if any)
- Link: (if any)
- Screenshot: (if any)
```

**Comment by andrewzah** [comment]
- Product: Navidrome by @deluan
- Link: https://github.com/deluan/navidrome

**Comment by JeffreyCA** [comment]
I love your work! 😃

- Product: Spleeter Web
- Link: https://github.com/JeffreyCA/spleeter-web
- Screenshot: 
    <img width="1022" alt="Screen Shot 2020-07-31 at 10 28 43 PM" src="https://user-images.githubusercontent.com/9157833/89092159-580f6c80-d37d-11ea-82bf-8e0b52cc904f.png">

**Comment by deluan** [comment]
- Product: Navidrome Music Server
- Link: https://www.navidrome.org
- Screenshot: 

<img width="1680" alt="Screen Shot 2020-08-01 at 12 04 55 AM" src="https://user-images.githubusercontent.com/331353/89093702-ad9e4600-d38a-11ea-899f-39cbb8ae38fe.png">

Thanks very much for you dedication!

**Comment by chaos87** [comment]
- Product: BackTube

- Link: https://backtube.netlify.app/

- Screenshot:

<img width="1790" alt="Screenshot 2020-09-01 at 8 24 12 AM" src="https://user-images.githubusercontent.com/30872370/91781297-8908e880-ec2c-11ea-82e6-f23f648d0b30.png">


Love the player, thanks for your support!

**Comment by DostalJ** [comment]
- Product: Catalogue of czech podcasts
- Link: [ceskepodcasty.cz](https://ceskepodcasty.cz/)
- Screenshot:
![Screenshot from 2020-10-01 16-17-44](https://user-images.githubusercontent.com/20856372/94821287-b69aaa80-0401-11eb-86c8-d8b50eb02d92.png)

**Comment by Dogson** [comment]
- Product：Des jeux et des mots - French aggregator of gaming videos and podcasts and sorting them by games.
- Link: https://desjeuxetdesmots.com
- Screenshot: 
![image](https://user-images.githubusercontent.com/6976364/104135284-9fb80c80-538f-11eb-94d2-37917d178520.png)

**Comment by sumit151199** [comment]
> * Product: BackTube
> * Link: https://backtube.app/
> * Screenshot:
> 
> <img alt="Screenshot 2020-09-01 at 8 24 12 AM" width="1790" src="https://user-images.githubusercontent.com/30872370/91781297-8908e880-ec2c-11ea-82e6-f23f648d0b30.png">
> 
> Love the player, thanks for your support!

Hey @chaos87  ,
Can you please help me,
 How  you manage player when you move from one player to another?

**Comment by chaos87** [comment]
@sumit151199 maybe open a separate issue, tag me, and give more context in what you try to achieve and what is blocking you.

**Comment by sumit151199** [comment]
> @sumit151199 maybe open a separate issue, tag me, and give more context in what you try to achieve and what is blocking you.
My issue is when I'm using a palyer Play well but when I'm moving from one page to another song play  from initial.  
How you manage player when you move from one page  to another?

**Comment by chaos87** [comment]
@sumit151199 the player must be at top level of your app so that when you change page it does not re-render your player. Feel free to lookup my repo it's all there.

**Comment by sumit151199** [comment]
> @sumit151199 the player must be at top level of your app so that when you change page it does not re-render your player. Feel free to lookup my repo it's all there.
when I'm running your code shows ERROR:×
TypeError: Cannot read property 'disable_all_events' of undefined
How to resolve this?

**Comment by lzx19951022** [comment]
-Product: show-control-system
-Description：this is a show-control-system for our daily live talk show based on React, thank you for making such a good music player. 
-screenshot:
![QQ20210629-144543](https://user-images.githubusercontent.com/35286852/123750550-4ca82680-d8e9-11eb-8d61-639f2354c22f.png)
![QQ20210629-144614](https://user-images.githubusercontent.com/35286852/123750561-52057100-d8e9-11eb-80ce-ec566cffb064.png)
![QQ20210629-144624](https://user-images.githubusercontent.com/35286852/123750574-55006180-d8e9-11eb-819a-383e1aff95bd.png)

**Comment by LinuxSuRen** [comment]
- Product：Open Podcasts
- Link: https://github.com/LinuxSuRen/goplay
- Screenshot:
