### ISSUE TITLE
Prevent auto scroll down to bottom after opening the player

### ISSUE THREAD

**Issue by rebeccadavidsson** [lijinke666/react-music-player#138]
### Description

After opening the Player with by clicking on the mini cover, the player gets rendered with 'position: fixed' at the bottom of the screen. However, this can be fixed when the element under the player has 'position: absolute'. Something to add to the README?

### Steps

```
<>
  <Player />
    <div className="main">
      <App />
    </div>
</>

```

css
```
.main {
   position: absolute;
}


```

**Comment by lijinke666** [comment]
The issue It's been fixed today. you can try latest version
