### ISSUE TITLE
audioTitle should expand to use available space

### ISSUE THREAD

**Issue by deluan** [lijinke666/react-music-player#141]
### Version
All versions

### Description
Seems that the `audioTitle` has a fixed max length, and does not use the available space in large windows.

### Expected Behavior
`audioTitle`should use the same space as the progress bar.

### Current Behavior
<img width="1680" alt="Screen Shot 2020-08-03 at 12 28 43 PM" src="https://user-images.githubusercontent.com/331353/89205363-9c6d5900-d585-11ea-9a5f-417983dcd518.png">

**Comment by lijinke666** [comment]
Fixed. please use latest version. thank your feedbackl
