### ISSUE TITLE
(Next.js) Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by DostalJ** [lijinke666/react-music-player#143]
I really enjoy the package, but it is not possible to be used with Next.js.

### Description
When importing the package I receive following error message.
```
error - ./node_modules/rc-slider/assets/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-jinke-music-player/es/index.js
```

It is [quite discussed problem](https://github.com/fullcalendar/fullcalendar/issues/5393) of Next.js. Is there any workaround with `react-music-player`?
Some more info can be found on [Next.js Github](https://github.com/vercel/next.js/blob/master/errors/css-npm.md) dedicated to this error.

### Version
Using package version 4.16.5 with Next.js 9.5.1.

**Thank you!**

**Comment by lijinke666** [comment]
https://github.com/lijinke666/react-music-player/blob/f267266728ff3c05a3d424e2ef18746df1a9296c/src/index.js#L60
Hi~, look i need remove this from `index.js`. i not used Next.js.
if you manual modify `./node_modules/react-jinke-music-player/es/index.js` , then remove it. can work fine ? can you try it in you locale env ?

**Comment by DostalJ** [comment]
I have [forked the repo](https://github.com/DostalJ/react-music-player) and in a special [branch](https://github.com/DostalJ/react-music-player/tree/next-js-fix) commented two lines importing .css. Then, in my Next.js project, I install the modified component directly from my Github fork and add the CSS files manually in `_app.js`.

**Works fine. Thank you!**

**Comment by lijinke666** [comment]
ok, have fun !

**Comment by emulienfou** [comment]
Hi @lijinke666 trying to use your package, however having the same issue with Next.js.

Is it possible for you to make some changes and load the 2 CSS files directly from your local less files instead of the `index.js` file of your package?

This will assure a compatibility with Next.js and also not using an outdated fork.

**Comment by lijinke666** [comment]
@emulienfou  Your are right, in `4.17.1` version, I have already move 2 css files from index.js to index.less. you can try it 🥇
