### ISSUE TITLE
How to use the updatePlayIndex function with Hooks?

### ISSUE THREAD

**Issue by AliAlAbbassi** [lijinke666/react-music-player#144]
I'm trying to access the updatePlayIndex with React Hooks. I tried getAudioInstance but it only returns an HTML element, I need to update the PlayIndex without re-rendering the component

**Comment by lijinke666** [comment]
Audio instance is extends [HTMLAudioElement](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLAudioElement) 

you can see the exapmle
[![Edit strange-on-audio-progress (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-on-audio-progress-forked-mg551?fontsize=14&hidenavigation=1&theme=dark)
