### ISSUE TITLE
Buttons do not work in Firefox when in compact player mode

### ISSUE THREAD

**Issue by deluan** [lijinke666/react-music-player#145]
### Version
4.17.0

### Description
When the player is full screen (in compact mode), most of the buttons on the bottom bar do not work (don't respond to clicks), in Firefox (and possibly Safari). It does work in Chrome

### Reproduce Link
https://www.lijinke.cn/react-music-player/

### Steps to Reproduce
Go to the demo site using Firefox, reduce the size of the screen to a mobile like size (see attached picture), and try clicking in any of the bottom buttons:

<img width="562" alt="Screen Shot 2020-08-20 at 10 30 41 AM" src="https://user-images.githubusercontent.com/331353/90785386-4829df00-e2d0-11ea-87a3-d281be8537b3.png">

### Expected Behavior
Clicks on the buttons trigger their respective actions

### Current Behavior
Seems like the click event is ignored. Nothing shows on the cosole when clicking the buttons

### System information
macOS Catalina, Firefox 79.0

### Comments
See related Navidrome issue: https://github.com/deluan/navidrome/issues/452

**Comment by lijinke666** [comment]
Ok, I'll take a look at it when I have time. thank you feedback

**Comment by lijinke666** [comment]
done.
