### ISSUE TITLE
Infinite load when append audio file

### ISSUE THREAD

**Issue by emulienfou** [lijinke666/react-music-player#146]
### Version
Latest version: **4.17.1**

### Description
When append a new audio file (here .m4a) and clicking on play, audio file seems to not be played directly.
Click on the item in the playlist again and the audio file will start to play.

However, audio file info seems to failed to be returned, the loading state loader is still displayed and no length is displayed in the player.

Also, a call seems to be made each time to an undefined endpoint, here was: `https://ccen8.csb.app/undefined` if you check you network console.

### Reproduce Link
[![Edit recursing-germain-ccen8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-germain-ccen8?fontsize=14&hidenavigation=1&theme=dark)

**Comment by irfiacre** [comment]
I have been having the same issue

**Comment by irfiacre** [comment]
Hello, How are you doing @lijinke666 
Any updates on the issue ??

Thank you.

**Comment by lijinke666** [comment]
I'll look over the problem when I have time, If you're in a hurry, welcome pr

**Comment by lijinke666** [comment]
@irfiacre Do you have reproduce link ?

**Comment by irfiacre** [comment]
This?
https://react-jinke-music-player.netlify.app/

**Comment by lijinke666** [comment]
the link cannot reproduce

**Comment by irfiacre** [comment]
There is a way I got around the issue.

**Comment by lijinke666** [comment]
@emulienfou i'm try in locale, it's work
![2020-08-28 17 00 17](https://user-images.githubusercontent.com/21015895/91542177-03491c80-e950-11ea-8c54-dab7d7b91183.gif)

**Comment by lijinke666** [comment]
@irfiacre I don't know what you're talking about

**Comment by irfiacre** [comment]
> @irfiacre I don't know what you're talking about, if you also have the infinite load issue, please tell some detail, the https://react-jinke-music-player.netlify.app/ online demo is work fine.
> 
> or you talk about?
> 
> > When appending a new audio file (here .m4a) and clicking on play, the audio file seems to not be played directly.
> > Click on the item in the playlist again and the audio file will start to play.

Yes this is what I am talking about

**Comment by emulienfou** [comment]
@lijinke666 To reproduce the bug, I made a sandbox example here: https://codesandbox.io/s/recursing-germain-ccen8?fontsize=14&hidenavigation=1&theme=dark

**Comment by lijinke666** [comment]
Done.

**Comment by lijinke666** [comment]
Infinite load fixed, ready release.

**Comment by lijinke666** [comment]
Done
