### ISSUE TITLE
Cannot change mode if drag disabled

### ISSUE THREAD

**Issue by emulienfou** [lijinke666/react-music-player#147]
### Version
Latest: **4.17.1**

### Description
If you disable option `drag`, you cannot switch from mini to full mode.

### Steps to Reproduce
1. Go to demo site: https://react-jinke-music-player.netlify.app/
2. Un-check option `drag`
3. Click to mini player to switch to full, nothing append

### Expected behavior
Switch from `mini` to `full` mode even if `drag` option is disabled

**Comment by lijinke666** [comment]
Done.
