### ISSUE TITLE
How do i update playlist?

### ISSUE THREAD

**Issue by hahatulk** [lijinke666/react-music-player#152]
Hi! I'm excited about your player. I think this is best reactjs player on NPM. But i cant understand how to update playlist directly. 
**E.G.** I have playlist of **100 items**. Some of them don't have **no audio source yet** (i generate it on backend) and i must add them **dynamically**. But i can only append audio, can't update it. Please i need your help! 😅

**Comment by lijinke666** [comment]
```tsx
const [audioLists, setAudioLists] = useState([])

useEffect(() => {
  someAjax('you backend api').then((data) => {
      setAudioLists(data)
  })
},[])

<ReactJkMusicPlayer clearPriorAudioLists audioLists={audioLists}/>
```

or 

```tsx
const audioInstance = useRef()
<ReactJkMusicPlayer getAudioInstance={ instance => audioInstance .current = instance }/>

audioInstance.current.appendAudio(index, audioLists)
```
