### ISSUE TITLE
Add Chromecast button

### ISSUE THREAD

**Issue by emulienfou** [lijinke666/react-music-player#153]
### Description
Would be nice to have a Chromecast button to be able to send audio to a Chromecast.
[React Cast Sender](https://github.com/AnteWall/react-cast-sender) package could be used to this feature.

### Expect Api Name
```
<ReactJkMusicPlayer chromecast={false}/>
```
> Allow the user to disable Chromecast feature (enabled by default)

**Comment by lijinke666** [comment]
Sounds like a nice feature. but it doesn't seem that universal, so the implementation of this feature will not be considered for now, or you can send a PR, thanks.
