### ISSUE TITLE
property "remember" does not seem to work

### ISSUE THREAD

**Issue by chaos87** [lijinke666/react-music-player#155]
Hi,

I was wondering when remember is True, does that mean the current playlist gets cached on the browser?

If not, what is it supposed to do?

Thanks a lot (as usual)!

**Comment by lijinke666** [comment]
`remember` originally designed as to remember like current play status, eg. `playIndex`, `playMode`, `currentTime`, but nobody seems to be using it. there may be some bugs,what do you want to do with it?

**Comment by chaos87** [comment]
Oh ok I see I got it working. Tbh not really useful for me either, and what I wanted to do (cache current playlist in browser) is actually best done with something like Local Storage.

**Comment by lijinke666** [comment]
Yes, you can use locale or session storage to set `audioLists` props, In a later release, maybe can cache audioLists by locale storage by remember props
