### ISSUE TITLE
Cannot select/play other songs when quietUpdate is used

### ISSUE THREAD

**Issue by deluan** [lijinke666/react-music-player#157]
### Version
4.18.0

### Description
When I change the audioLists using the `quietUpdate` option, I cannot skip songs, nor can I click on a different song in the play queue.

### Steps
Go to the the demo site https://www.lijinke.cn/react-music-player/, click on "Play", then on "quiet update audio list". Now if you try to "play next" or if open the play queue, you can't change to another song

### Reproduce Link
https://www.lijinke.cn/react-music-player/

### Expected Behavior
The user is able to change the playing music in the same way as if the `quietUpdate` option was not used

### Current Behavior
User cannot change the playing music if `quietUpdate` was used

No errors are logged in the console

### System information
Tested in macOS, Chrome 84.0.4147.135 and Firefox 79.0 

### Comments
Thanks for your continuing efforts to make this the best React player out there!

**Comment by lijinke666** [comment]
Fixed
