### ISSUE TITLE
Player won't load music during update audioList state with redux.

### ISSUE THREAD

**Issue by cudouny** [lijinke666/react-music-player#16]
Hey, got a problem with updating track list update using redux.

```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import ReactJkMusicPlayer from 'react-jinke-music-player';
import '../music-player/player.css';

@connect(({ PlayerTracks }) => ({
  tracks: PlayerTracks.tracks,
}))
export default class Container extends PureComponent {
  static propTypes = {
    tracks: PropTypes.array,
  }

  static defaultProps = {
    tracks: null,
  }

  render() {
    const { tracks } = this.props;
    return (
      <div>
        <ReactJkMusicPlayer drag={false} showThemeSwitch={false} mode='full'
                            showDownload={false} toggleMode={false}
                            audioLists={tracks} autoPlay={false}/>,
      </div>
    );
  }
}
```
If I have initial state like an empty array future update of audioList break ability to play any sound. If I define initial array with some data it's ok, but if I try to clearely update whole list smth went wrong:(
P.S. player is really awesome, thanks!:)

**Comment by lijinke666** [comment]
Thanks for you feedback :)
I did not try it under the `redux` environment
I will look at this bug as soon as possible and try to fix it

**Comment by lijinke666** [comment]
@cudouny 
Hi~ Please try use `react-jinke-music-player@3.4.2` , See if there are any questions, welcome feedback

**Comment by cudouny** [comment]
@lijinke666 
Hey, fix works fine, FYI, I have a couple ideas of features for the player, if you intrerested in this. Thanks in advance!

**Comment by lijinke666** [comment]
@cudouny if you have some ideas , please open a new issue . we can discuss sharing together . 
of course , you can also send a `pr` for you :+1:
