### ISSUE TITLE
Clicking on the progress bar makes the player reload the current music

### ISSUE THREAD

**Issue by Dogson** [lijinke666/react-music-player#162]
### Version
4.18.2

### Description
The player reload itself when clicking anyway on the progress bar.

### Codelink
https://codesandbox.io/s/strange-on-audio-progress-forked-jggck

### Note
This seems to be a regression, the same code runs flawlessly under version 4.16.5
https://codesandbox.io/s/strange-on-audio-progress-forked-9wof9?file=/package.json

**Comment by DostalJ** [comment]
Same problem here. _I guess it is something with the mechanism of loading the audio._

**Comment by lijinke666** [comment]
This should be the result of refactoring the code. Thanks for the feedback, I'll look at it when I have time

**Comment by lijinke666** [comment]
done
