### ISSUE TITLE
Cannot return to full screen from the mini-player when in a mobile device

### ISSUE THREAD

**Issue by deluan** [lijinke666/react-music-player#163]
### Version
4.8.2, but this has been happening for a while, at least since 4.6.0

### Description
When the player is full screen (in compact mode), if you change it to the mini-player you cannot get back to full screen by touching/clicking the floating mini player cover.

### Reproduce Link
https://www.lijinke.cn/react-music-player/

### Steps to Reproduce
1. Using an Android device, go to the demo site
2. Start the player (touch the "play" button)
3. Close the player using the little "x" button on the top right. Now the player is in "mini" mode
4. If you now touch the floating mini player, it does not go back to full screen.  

### Expected Behavior
When touching the mini-player, it should go back to full screen, as it happens when using Chrome in a desktop/laptop computer.

### Current Behavior
Nothing happens when the floating mini-player is touched

### System information
Tested with Chrome on Android 10 and 11

### Comments
By the way, is there a way to use the mobile version of the full-screen player in a with larger screen, as opposed to having the player as a bar in the bottom of the screen?

**Comment by lijinke666** [comment]
I use `react-draggable` to implementation drag feature for mini mode, but the lib will trigger `onDrag` event when touched mini mode on Android device, so cannot toggle to full screen. I improved and fixed on this issue. It works fine on my Android device. please wait for the new release

> By the way, is there a way to use the mobile version of the full-screen player in a with larger screen, as opposed to having the player as a bar in the bottom of the screen?

What is the usage case? maybe for ipad ?

**Comment by deluan** [comment]
Thanks for taking care of this, really appreciate your efforts!
> What is the usage case? maybe for ipad ?

A user of my music server is trying to use it on a Raspberry Pi 7" display: https://github.com/deluan/navidrome/issues/520. I think it would also be useful for tablets, to give the user the option to have the player in full screen or as a bar at the bottom

**Comment by lijinke666** [comment]
Sounds like a good idea, If I have time, I will implement this feature, i will open a new feature
