### ISSUE TITLE
showDownload error in types

### ISSUE THREAD

**Issue by Kahore** [lijinke666/react-music-player#177]
### Description
if we look at the index.ts.d we will see that `showDownload ` belongs to `onAudioListsDragEnd `but it should be at the top level.
Isn't it?

`
  onAudioListsDragEnd?: (
    currentPlayId: string,
    audioLists: Array<ReactJkMusicPlayerAudioListProps>,
    audioInfo: ReactJkMusicPlayerAudioInfo,
    showDownload?: boolean
  ) => void,
`

**Comment by lijinke666** [comment]
Thanks.
