### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by nunojesus** [lijinke666/react-music-player#19]
Hello, I like to contribute with graphic designs, in opensource projects, so if you need something from me like a logotype or something else just say it, Im here ready to help you.
Love the screenshots of your player
Greetings!
Nuno Jesus

**Comment by lijinke666** [comment]
@nunojesus  If this project can have a beautiful logo, it must be excellent . 
Are you offering it for free ：）
Looking forward to your pr

**Comment by nunojesus** [comment]
Great!

So let´s begin, do you have any request for the logo? Shape? Colors?

It´s only for desktop, are you thinking to make a app to android and ios too?

Greetings!

**Comment by lijinke666** [comment]
The Player  primary color is `#31c27c` .  I don't know much about design.
the repo is a react components .this is a web application .  so i hope  It could be a combination of react and music.

**Comment by nunojesus** [comment]
Hi, Im sorry for the late reply, tomorrow I will make try to show some design that I made for you. Greetings!

**Comment by lijinke666** [comment]
@nunojesus Look forward to! I'm going to release version 4.0 tomorrow. I hope to add your logo in this version.

**Comment by nunojesus** [comment]
Hello, see if you like one of this designs?

Greetings!

![react](https://user-images.githubusercontent.com/34600369/40932418-2cddb1da-6826-11e8-93e1-a98a6518c096.png)

**Comment by lijinke666** [comment]
@nunojesus  Hi~ i think the first logo is very nice !  What happens if replace `#31c27c`

**Comment by nunojesus** [comment]
Hi, Im happy that you like it, I will change the color and send you again. Greetings!

**Comment by nunojesus** [comment]
Hello, I change the color as you requested, I create also diferent sizes of logo to see what it works best in small sizes.

I like much the 1st and the 2nd

In the end you have png files of this logos, just tell wich one you like to create all the files of the logo, by the way what kind of font you like?

Greetings!


![react size](https://user-images.githubusercontent.com/34600369/40965674-49882682-68a6-11e8-986b-d9fd7d44fa00.png)

## 1st
![react3](https://user-images.githubusercontent.com/34600369/40965982-2376b250-68a7-11e8-85a2-04cd65235014.png)

## 2nd
![react1](https://user-images.githubusercontent.com/34600369/40965683-56750284-68a6-11e8-9d67-b483d8398ec5.png)

## 3rd
![react2](https://user-images.githubusercontent.com/34600369/40965691-5a240786-68a6-11e8-80ae-24017cc6da34.png)

**Comment by lijinke666** [comment]
@nunojesus Thank you for your contribution. You are a great designer. I have added the icon to the project description.
:+1:

**Comment by nunojesus** [comment]
Great, tomorrow I will make a PR with the png files and svg files. Greetings!
