### ISSUE TITLE
Hide the player when the length of audio lisits is 0

### ISSUE THREAD

**Issue by leventdeniz** [lijinke666/react-music-player#191]
### Description

I think it would be nice if the player would be hidden (not unmounted) if the length of the audio list is 0

### Expect Api Name
could be optional api parameter:
`hideIfEmptyList?: boolean`

**Comment by lijinke666** [comment]
Why need the api ? why not:

```jsx
yourAudioLists.length ? <ReactJkMusicPlayer/> : null
```
