### ISSUE TITLE
UX: Don't disable media controls when buffering

### ISSUE THREAD

**Issue by grahamotte** [lijinke666/react-music-player#197]
Original issue: https://github.com/deluan/navidrome/issues/568

---

I run navidrome on a linode and I'm currently somewhere with less than perfect internet. When I click next to skip a song this spinner comes up:

<img width="432" alt="Screen Shot 2020-10-12 at 10 34 05 PM" src="https://user-images.githubusercontent.com/6063967/95819742-8abdd580-0cdb-11eb-8458-48b63bd097ca.png">
<img width="432" alt="Screen Shot 2020-10-12 at 10 34 42 PM" src="https://user-images.githubusercontent.com/6063967/95819711-77ab0580-0cdb-11eb-81e1-6c3aaaed0369.png">

However if I also want to skip the next song, this can be pretty annoying since I need to wait for it to buffer before I'm allowed to click next again. 

Perhaps the solution is simply to cleanup my music library but it would be great if I was allowed to quick skip to the next song. 

Cheers

**Comment by lijinke666** [comment]
done
