### ISSUE TITLE
New features to the player

### ISSUE THREAD

**Issue by cudouny** [lijinke666/react-music-player#20]
Hey @lijinke666 , here is the list of features that could be awesome for your player

- On track list state change start auto-playing this list.
For the first case you have an 3 tracks that loaded to your list, when list changed, player **automatically** starts playing from first track of the list
- Make some kind of **flag in the request array** which track to play.
You have array of tracks info, as for now they played from the first one, we need to add some **flag** to alert the player that tracks playlist should **start from some index**
- Make track list bar **customizible**, I mean, we need to add some **delete** button for modifying this list if you want to drop this track from **playing queue**.
- **Ordering** in play queue, need to add some kind of track position **dragging**, click on track, drag out it to the first position of the queue etc.

Thanks a lot!

**Comment by lijinke666** [comment]
@cudouny  What you're saying is that every song in this playlist can be pushed in an arbitrary way ?
![image](https://user-images.githubusercontent.com/21015895/40266328-e06c8ddc-5b7b-11e8-836c-bd9ea0e78868.png)

Then you want add a new Feature 
audio list  add a `delete button` , like click the button can `remove` current the audio ?

Let's say the second song is playing.  then redux update  or replace the audio lists . 
Do you want to play the second song after the update?

or add a new api  like `audioDelete` trriger after the remove. 
like this ? 
```
const options = {
   audioDelete(audio,currentPlayerId){
       audio.play(YOUR_WANT_TO_PLAY_ID)
  }
}
```

**Comment by cudouny** [comment]
Hi @lijinke666, sorry for long response.
> @cudouny What you're saying is that every song in this playlist can be pushed in an arbitrary way ?
![image](https://user-images.githubusercontent.com/32036813/40482053-14eedbbc-5f5c-11e8-8f66-0d805e843b25.png)
I mean if you try to hold down click button,  you can like,  swap tracks in the playing queue.
For the feature with delete button behavior.
![image](https://user-images.githubusercontent.com/32036813/40481770-15687c34-5f5b-11e8-9ef7-936ba15de692.png)
For example, it's just a feature when you need to remove some track from playing queue. If track that you currently playing is clicked to delete, you just remove this track from the queue and start playing next track, or nothing in case of empty playing queue.
Please, ask me any questions about this.
Thank you!

**Comment by lijinke666** [comment]
I know what you mean, you want the list to drag and drop or can delete it
That sounds good and I'll try it on a new branch
Thank you for your advice ：）

**Comment by lijinke666** [comment]
@cudouny Hi~ The branch `feat-4.0.0`  
You have completed the features you want and are expected to be released tomorrow
Looking forward to your feedback and use
![image](https://user-images.githubusercontent.com/21015895/40922214-3c892db2-6844-11e8-8d45-dade1ad0486b.png)

have fun! 💯
