### ISSUE TITLE
no lyrics !! 

### ISSUE THREAD

**Issue by pooooriya** [lijinke666/react-music-player#205]
### Description
Hello , I have lyrics on my music but player doesnt show them , and says no lyrics !!
### Steps to Reproduce
make api call for your musics and give lyrics as props to player 
### Expected Behavior
shows my lyrics
### Current Behavior
doesnt show my lyrics

Version 86.0.4240.111 (Official Build) (64-bit)
### System information
linux ubonto 20.04

**Comment by lijinke666** [comment]
Need code, screenshots, and reproduce Link

**Comment by pooooriya** [comment]
cassettify.ir --- all my music have lryics in persian but its says no lyrics
