### ISSUE TITLE
Spelling mistake on reload hover button. 

### ISSUE THREAD

**Issue by sahildua93** [lijinke666/react-music-player#21]
Music Player - Name of the title/tool-tip should be **reload** instead of **roload** on reload button hover.

**Comment by lijinke666** [comment]
@sahildua93 Thanks you feedback. But I don't seem to misspelling . Can you show me a picture?

**Comment by lijinke666** [comment]
@sahildua93 In the example I am actually wrong . Thanks for your feedback, I have fixed it
