### ISSUE TITLE
Drag playlist items seems not working on mobile

### ISSUE THREAD

**Issue by chaos87** [lijinke666/react-music-player#223]
I'm using version 4.19.0

I encounter difficulties in shuffling songs in the playlist panel using mobile version (with responsive mode). I believe this should be smooth like dragging songs on the desktop version.

My website, if you want to try on your mobile phone: https://backtube.app
Thanks for your help!

**Comment by lijinke666** [comment]
https://github.com/raisezhang/react-drag-listview/issues/42
Play list drag feature use by [react-drag-listview](https://github.com/raisezhang/react-drag-listview), i think the drag itself conflicts with the gestures on the mobile,
