### ISSUE TITLE
Cannot Fire onPause, onEnd, etc

### ISSUE THREAD

**Issue by steveambielli** [lijinke666/react-music-player#23]
I'm new to React. I have my component set up this way and it fires the function on mount. What am I doing wrong? Thanks!

`<ReactJkMusicPlayer
              ...
              onAudioProgress={this.trackTime('progress')}
              onAudioEnd={this.trackTime('end')}
              onAudioPause={this.trackTime('pause')}
            />`

**Comment by lijinke666** [comment]
@steveambielli  What is `trackTime()` ?  I think you maybe write like this
```jsx
class Test extends React.Component {
   ...
   trackTime = (type,audioInfo) =>{

   }
   render(){
      return (
             <ReactJkMusicPlayer onAudioProgress={ (audioInfo)=> this.trackTime('progress',audioInfo)} />
      )
   }
}
```

**Comment by steveambielli** [comment]
Thanks for the reply! `trackTime()` is a function I'm using to track the listener time.  I added your syntax to the component but console is not outputting anything. I also want to apply this to OnAudioEnd and onAudioPause.

`class Player extends Component {
constructor(props) {
    this.trackTime = this.trackTime.bind(this);
}
trackTime(action) {
    console.log(action);
}

render() {
  return (

    <ReactJkMusicPlayer
        ...
        onAudioProgress={ (audioInfo)=> this.trackTime('progress', audioInfo)}
        onAudioPause={ (audioInfo)=> this.trackTime('pause', audioInfo)}
    />
  )
}`

**Comment by lijinke666** [comment]
@steveambielli  Hi~ 
First please check your current installed version. The latest version is 4.0.1
There is a slight change in api and 3.x

if you want upgrade the player
```
yarn upgrade react-jinke-music-player@4.0.1
```

If it is a version issue , you should know diff of `4.x` and `3.x`

```jsx
//3.x
<ReactJkMusicPlayer audioPause={} audioProgress={}  audioEnd={}/>

//4.x
<ReactJkMusicPlayer onAudioPause={} onAudioProgress={} onAudioEnd={}/>
```

If the version is up-to-date, but there are still problems please tell me : )

Have Fun !!

**Comment by steveambielli** [comment]
I upgraded to 4.0.1 and with the same code as above, my console remains quiet.

**Comment by lijinke666** [comment]
This is my test code 
![image](https://user-images.githubusercontent.com/21015895/41041793-a8072ec4-69d2-11e8-9f2a-05007283f6ce.png)
![image](https://user-images.githubusercontent.com/21015895/41041812-b6d800c2-69d2-11e8-9a17-7d177d817a72.png)

First of all you have to make sure that your song is playing .
These several functions are triggered after the song is played . 
Make sure this parameter is not an empty array and audioLists src resources are available
```
<ReactJkMusicPlayer 
   audioLists=[{ 
      name: "xx",
      singer: "xx",
      cover: "xx",
      musicSrc: "xx.mp3"
    }]
 />
```

Please see the [example](https://github.com/lijinke666/react-music-player/blob/master/example/example.js)

**Comment by steveambielli** [comment]
The list I'm using does not have all of the parameters. I'm only passing name and musicSrc. I updated it to pass all even if there is no data. The playlist loads, the song plays, but console outputs nothing.

The playlist is dynamically generated via a fetch to my PHP server where the return is a JSON array. Does it make a different that my syntax is JSX? Your syntax is a little different than mine. What's odd is that the response from my web-api for the playlist of songs says it's an empty array, but the player successfully loads it and plays the music. However, when I log the response I see a correct array.

```
import React, { Component } from 'react';
import ReactJkMusicPlayer from "react-jinke-music-player";
import Playlists from './Playlists';
import "react-jinke-music-player/assets/index.css";
import '../css/player.css';
import $ from 'jquery';

class Player extends Component {
   constructor(props) {
       super(props);
       this.trackTime = this.trackTime.bind(this);
   }

   trackTime(action, audioInfo) {
       console.log(action);
   }

render() {
     return (
        <ReactJkMusicPlayer
              audioLists={this.state.playlist}
              mode="full"
              autoPlay={false}
              toggleMode={true}
              showReload={false}
              showDownload={false}
              showPlayMode={false}
              showThemeSwitch={false}
              extendsContent={[
                  <i className="fa fa-heart add-song" aria-hidden="true" title="Add this song" key="heart" onClick={this.addSong} data-toggle="modal" data-target=".modal"></i>,
                  <i className="fa fa-star rate-song" aria-hidden="true" title="Rate this song" key="rate" onClick={this.rateSong} data-toggle="modal" data-target=".modal"></i>,
                  <i className="fa fa-bars playlists" aria-hidden="true" title="Open playlists" key="playlists" onClick={this.showPlaylists}></i>
                ]}
              panelTitle={this.state.playlistTitle}
              onAudioProgress={ (audioInfo)=> this.trackTime('progress', audioInfo)}
              onAudioPause={ (audioInfo)=> this.trackTime('pause', audioInfo)}
            />
        );
    }
}
}
```

**Comment by steveambielli** [comment]
Welp, I got it working. :) Thanks for your help!
