### ISSUE TITLE
Dynamically adding playlist but it only plays only one song on-next-up

### ISSUE THREAD

**Issue by muiezarif** [lijinke666/react-music-player#232]
const initialState = {
    clearPriorAudioLists: false,
    spaceBar: true,
    params: {},
    autoPlay:true,
    quietUpdate:true,
    songData: [],
    defaultPosition: {
        bottom: 100,
        right: 10
    }
}

class AudioPlayer extends React.Component {
    constructor() {
        super();
        this.audio = null
    }

    state = initialState

    componentDidUpdate(prevProps, prevState, snapshot) {
        const myPrevProps = prevProps
        
        if ((this.props.songData !== myPrevProps.songData)) {
            this.setState({songData: {}, clearPriorAudioLists: true})
            const data = [{
                name: this.props.songData.data.song_title,
                singer: this.props.songData.data.description,
                cover: this.props.songData.data.photo_main,
                musicSrc: this.props.songData.data.audio_file,
            }
            ]
             let dataAddList = []
             dataAddList = this.props.songData.playlist.map(item =>{
                 console.log(item)
                 return {
                     name: item.song_title,
                     singer: item.description,
                     cover: item.photo_main,
                     musicSrc: item.audio_file
                 }
             })
            this.setState(initialState)
            this.setState({songData: data, clearPriorAudioLists: true,quietUpdate: true, spaceBar: true,autoPlay:true})
           
        }
       

    render() {
        return (
            <div ref={this.focusPlayer}>
                <ReactJkMusicPlayer className="music-player-custom" defaultPosition={this.state.defaultPosition}
                                    audioLists={this.state.songData}
                                    loadAudioErrorPlayNext={true}
                                    responsive={false}
                                    autoPlay={this.state.autoPlay}
                                    remove={false}
                                    spaceBar={this.state.spaceBar}
                                    quietUpdate={this.state.quietUpdate}
                                    toggleMode={true}
                                    mode="full"
                                    defaultPlayMode= 'orderLoop'
                                    showDestroy={false}
                                    showDownload={false}
                                    clearPriorAudioLists={this.state.clearPriorAudioLists}
                                    showPlayMode={false}
                                    getAudioInstance={(audio) => {
                                        this.audio = audio
                                    }}
                />
                {}
            </div>
        );

    }

}
### Steps

```js
/**
 * code
 */
```

**Comment by lijinke666** [comment]
Need Reproduce Link

**Comment by muiezarif** [comment]
thanks but i got the hang of it i was doing it differently thanks.
