### ISSUE TITLE
Lyrics not working for Single Song plays

### ISSUE THREAD

**Issue by SurajMazar** [lijinke666/react-music-player#241]
### Description
while audio list changes lyrics doesnt change

### Steps

herre are my audio lists

`const audioList1 = [{
   key:1,
  name:'Linkin Park - In The End from audio list 1',
  singer:"Linkin Park",
  cover:DummyImage,
  lyric:'[00:05.00]linkin park from audiolist 1',
  musicSrc:'https://songs-nepal-api-prod.s3.amazonaws.com/uploads/songs/song_files/2020/08/Coldplay_-_Paradise__Official_Video_.mp3',
},]

const audioList2 = [{
  key:2,
  name:'Linkin Park - In The End from audio list 2',
  singer:"Linkin Park",
  cover:DummyImage,
  lyric:'[00:03.00] from audio list 2',
  musicSrc:'https://songs-nepal-api-prod.s3.amazonaws.com/uploads/songs/song_files/2020/08/Coldplay_-_Paradise__Official_Video_.mp3',
},]

const [testAudioList,setTestAudioList] = useState(audioList1) // current state for audio list

const changeDemoAudioList = ()=>{  //function to change audio list
    setTestAudioList(audioList2)
  }

const options ={
    defaultPlayIndex: 0,
    theme: 'light',
    bounds: 'body',
    quietUpdate: false,
    clearPriorAudioLists: true,
    autoPlayInitLoadPlayList: true,
    preload: true,
    glassBg: false,
    remember: false,
    remove: true,
    defaultPosition: {
        right: 100,
        bottom: 120,
    },
    mode: 'full',
    once: false,
    autoPlay: true,
    toggleMode: true,
    showMiniModeCover: true,
    showMiniProcessBar: false,
    drag: true,
    seeked: true,
    showMediaSession: true,
    showProgressLoadBar: true,
    showPlay: true,
    showReload: true,
    showDownload: false,
    showPlayMode: true,
    showThemeSwitch: false,
    showLyric: true,
    showDestroy: false,
    extendsContent: null,
    defaultVolume: 1,
    playModeShowTime: 600,
    loadAudioErrorPlayNext: true,
    autoHiddenCover: false,
    spaceBar: true,
    responsive: true,
    getContainer() {
        return document.body
    },
    onBeforeDestroy(currentPlayId, audioLists, audioInfo) {
        return new Promise((resolve, reject) => {
            if (window.confirm('Are you confirm destroy the player?')) {
                resolve()
            } else {
                reject()
            }
        })
    },
    onDestroyed(currentPlayId, audioLists, audioInfo) {
    },
    onCoverClick(mode, audioLists, audioInfo) {
    },

 // button that changes audiolist//
 <button onClick={changeDemoAudioList} style={{zIndex:"99999",position:"relative"}}>test audio change</button>
 <ReactJinkeMusicPlayer
          audioLists={testAudioList}
          {...options}
          onAudioListsChange={onAudioListsChange}
        />

```

### Reproduce Link

### Steps to Reproduce

### Expected Behavior
while audiolist changes song lyrics should change according to the song


### Current Behavior
while playing single songs the lyrics of the current song is shown while audiolist chages everything except the lyric doesnt change(clear priority queue is set true )
This wont occurr when the songs are in bulk (more than one) or when (clear priority queue is set false)


Please provide me a suggestion .. thank you
<!-- browner console log -->

### System information
![image](https://user-images.githubusercontent.com/49373020/103607604-6e7bae80-4f41-11eb-8406-ae2999210046.png)
![image](https://user-images.githubusercontent.com/49373020/103607642-87845f80-4f41-11eb-8f11-4ae0305d1a08.png)

### Comments

**Comment by lijinke666** [comment]
Can you give a reproduce link ?

**Comment by SurajMazar** [comment]
> 
> 
> Can you give a reproduce link ?

Dear Sir/Mam , i have updated my issue.. kindly please provide me a suggeestion .. Thank you :)
