### ISSUE TITLE
Timestamp shows 00:60 instead of 01:00

### ISSUE THREAD

**Issue by JeffreyCA** [lijinke666/react-music-player#242]
### Version
Latest

### Description
The timestamp goes from `00:59` to `00:60` to `01:01`.

### Steps
1. Go to demo site: https://www.lijinke.cn/react-music-player/
2. Play track from around `00:55`
3. Observe the left timestamp

### Expected Behavior
The timestamp goes from `00:59` to `01:00` to `01:01`.

### Current Behavior
The timestamp goes from `00:59` to `00:60` to `01:01`.

### System information
macOS 11.1

### Video

https://user-images.githubusercontent.com/9157833/103297925-47fcc700-49c7-11eb-9892-ff480de6f55e.mov

**Comment by JeffreyCA** [comment]
I think it can be fixed by changing `s > 60` to `s >= 60` here:

https://github.com/lijinke666/react-music-player/blob/e88b857cda4d392086f947c4f4ff39bb3e970449/src/utils.js#L6-L13

**Comment by lijinke666** [comment]
Fixed. thanks
