### ISSUE TITLE
Add support for youtube urls in audioList 

### ISSUE THREAD

**Issue by MistreanuIonutCosmin** [lijinke666/react-music-player#245]
Hello,

Let me start by saying that I really love the design and functionality of this player.
What I miss is the functionality to play youtube content, not only .mp3 songs. This will make this extension so more versatile.

I don't see the need for any API change, because it's easy to distinguish with a regex between an URL with youtube in it and one without.
https://www.youtube-nocookie.com/embed/rHh1uQndXJ4

Thank you!

**Comment by BilalurRehman-27** [comment]
Hey.
I have forked your PR from git. And I am actively seeing your mails on the development of this feature. 
I must say that its a very good extension. Keep up the good work. And  best of luck :)

Regards BilalurRehman

**Comment by lijinke666** [comment]
Weclome PR.
