### ISSUE TITLE
Scope ul in index.css

### ISSUE THREAD

**Issue by steveambielli** [lijinke666/react-music-player#25]
I'm using this awesome component within an app I'm building, but I noticed the styles for unordered list is not scoped to just the player; therefore, the global style inherits it. Can you scope it? Thanks!

**Comment by lijinke666** [comment]
@steveambielli I will fix it as soon as possible! I’m a bit busy recently, I didn’t get back to you in time Sorry

**Comment by lijinke666** [comment]
@steveambielli  Hi~ i'm fix `@4.0.2`
