### ISSUE TITLE
ci token

### ISSUE THREAD

**Issue by xrkffgg** [lijinke666/react-music-player#251]
看了一下，有几个 CI token 填的 antd 的，到时候会报错的，可移除，或使用默认约定的 GITHUB_TOKEN

若需要 issues-helper 展示的话，提供下项目链接和 logo url

**Comment by lijinke666** [comment]
好的, 感谢,已修改
项目链接: https://github.com/lijinke666/react-music-player
logo: https://github.com/lijinke666/react-music-player/blob/master/assetsImg/logo.png

**Comment by xrkffgg** [comment]
https://github.com/lijinke666/react-music-player/blob/master/assetsImg/logo.png?raw=true  这个地址才能查看的
