### ISSUE TITLE
Issues with fade-in/fade-out

### ISSUE THREAD

**Issue by JeffreyCA** [lijinke666/react-music-player#256]
### Version
Latest

### Description
If you specify a fade-out duration, when you click Pause, the icon switches to "Pause" when the audio is completely faded (results in a ~1 sec lag, feels awkward). But it should change immediately after clicking it, regardless of the fade value.

### Reproduce Link
https://www.lijinke.cn/react-music-player/

**Comment by JeffreyCA** [comment]
@lijinke666 I opened a PR to fix several issues with the volume fade-in/fade-out. Can you please take a look when you have time?

**Comment by lijinke666** [comment]
Awesome!!! Thank you for your work
