### ISSUE TITLE
Firefox Audio Src

### ISSUE THREAD

**Issue by steveambielli** [lijinke666/react-music-player#26]
In Firefox and Edge, the audio source does not load.

Console:
`Invalid URI. Load of media resource  failed.`

DOM:
`<audio class="music-player-audio" src="https://domain.com/path_to_mp3"></audio>`

It works fine in Chrome. Any thoughts? I'm loading the audioList from a fetch which updates the state in the component.

**Comment by lijinke666** [comment]
@steveambielli 
I only tested it in Google Chrome
I will try to fix it
Thanks your feedback : )

**Comment by lijinke666** [comment]
This is browser support for audio formats 

![image](https://user-images.githubusercontent.com/21015895/41276010-635758e4-6e55-11e8-97c9-24dc12cbc6a6.png)

if you want suport `Firefox`, i'think you should use `ogg` format .

**Comment by steveambielli** [comment]
Can there be an option for a fallback in Firefox/Opera?

**Comment by steveambielli** [comment]
Update: Firefox does support .mp3. I just tested a simple <audio controls src="xxx"></audio> and it played. Is there another reason? Also, on mobile it's not playing.

**Comment by lijinke666** [comment]
sorroy,I haven't replied you for such a long time. I'm a little busy recently. I'll check it as soon as possible

**Comment by lijinke666** [comment]
> mobile it's not playing.

yes, it's a bug, i'm try fix it

**Comment by steveambielli** [comment]
Is there anyway I can help you get this working?

**Comment by steveambielli** [comment]
Hello. Any updates?

**Comment by lijinke666** [comment]
@steveambielli  Please update version `react-jinke-music-player@4.0.3` , try again
It looks like it should play on the phone, but beacuse pending audio loading  (audio network state ) 0 => 3,  An error is triggered and the next song is played by default ,

loading audio => pending network state change => emit error => play next audio

so
It's a little bit of a logical conflict, and I need to take some time to process it

**Comment by steveambielli** [comment]
Thanks for working on this! I updated to 4.0.3 but it's still not playing in Firefox (desktop), Safari (mobile) and Chrome (mobile). It's working on Chrome (desktop). Any ideas what's going on? Thanks!

**Comment by tanmynguyen** [comment]
hi @steveambielli . I try with version 4.0.4.
1. Worked: desktop(chrome, firefox),
2. Not Work:  desktop(Safari) mobile,

**Comment by lijinke666** [comment]
I am sorry that I am free to maintain this project recently 
I publish `4.1.0` version fixed some issue . now

😁 Firefox is work
![image](https://user-images.githubusercontent.com/21015895/52335522-8e488600-2a3d-11e9-9fc8-402c26f5d737.png)


😁 Safari is work (desktop and mobile)
![image](https://user-images.githubusercontent.com/21015895/52335458-6b1dd680-2a3d-11e9-978a-2400e98ca999.png)

I also fixed some weird problems , Playing audio on mobile is annoying .

good luck, have fun
