### ISSUE TITLE
Seeking problem solving

### ISSUE THREAD

**Issue by mohammadgolche** [lijinke666/react-music-player#283]
seeking problem solving ==>
 step: 0.05 to 1

# ./config/slider.js
```js
export var sliderBaseOptions = {
  min: 0,
  step: 1
};

```
#283

**Comment by lijinke666** [comment]
Can you provide more information?

**Comment by mohammadgolche** [comment]
> Can you provide more information?

seekbar and track sometimes stuck when seeking.
i solved #283
