### ISSUE TITLE
How to change musicSrc onPlay?

### ISSUE THREAD

**Issue by bl4ckck** [lijinke666/react-music-player#284]
```js
const onPlay = (audioInfo) => {
    return audioInfo.musicSrc = audioInfo.musicSrc + "&authuser=" +Cookies.get("authuser");
  }

<PlayerWithNoSSR audioLists={data} onAudioPlay={onPlay} />

```

**Comment by lijinke666** [comment]
Why do I need to add it after playing? 

i think should map your data ?

```jsx
const audioLists = data.map(({musicSrc, ...item}) => ({musicSrc: `${musicSrc}&authuser=${Cookies.get("authuser")}`, ...item}))

<PlayerWithNoSSR audioLists={audioLists} />
```

**Comment by bl4ckck** [comment]
Yeah, map should be fine in my case, I'm using it in backend to add those parameter. But I think change the URL on audio playing is better than map all of the data to add a simple parameter.

**Comment by lijinke666** [comment]
i think the player should be a controlled components ,i think uptate music src by hook function, although simple, but unreasonable
