### ISSUE TITLE
Forward/Backward seeked custom icon

### ISSUE THREAD

**Issue by sumit151199** [lijinke666/react-music-player#305]
Hey Team, 
I need to add custom forward/backward seeked icon like play/pause.
Please suggest me
Thank you

**Comment by lijinke666** [comment]
Use `extendsContent` and `getAudioInstance`

```tsx
let audio = useRef(null)

return (
  <ReactJkMusicPlayer
    getAudioInstance={(instance) => (audio.current = instance)}
    extendsContent={
      <>
        <ForwardIcon onClick={(audio.current.currentTime = xxx)} />
        <BackwardIcon onClick={(audio.current.currentTime = xxx)} />
      </>
    }
  />
)
```

**Comment by sumit151199** [comment]
> Use `extendsContent` and `getAudioInstance`
> 
> ```tsx
> let audio = useRef(null)
> 
> return (
>   <ReactJkMusicPlayer
>     getAudioInstance={(instance) => (audio.current = instance)}
>     extendsContent={
>       <>
>         <ForwardIcon onClick={(audio.current.currentTime = xxx)} />
>         <BackwardIcon onClick={(audio.current.currentTime = xxx)} />
>       </>
>     }
>   />
> )
> ```

Thank you

**Comment by sumit151199** [comment]
Hellon , 
I'm facing issue on 10 sec forward and 10 sec backward seek  sometimes it works sometime not, When I'n changing the song then it not works.

`onProgressChangeForward = (currentTime) => {

    if (this.audio) {
      this.audio.currentTime = currentTime + 10
    }
    this.setState({ currentTime, isAudioSeeking: true })
  }
  onProgressChangeBack = (currentTime) => {
    if (this.audio) {
      this.audio.currentTime = currentTime - 10
    }

    this.setState({ currentTime, isAudioSeeking: true })
  }`
