### ISSUE TITLE
Customise loader

### ISSUE THREAD

**Issue by sumit151199** [lijinke666/react-music-player#316]
How to customize lader in extendsContent.
extendsContent ={

 isPlaying ?
 <Play onClickBtn={() => {
this.audio.play()
  }} />
:
<Pause onClickBtn={() => {
 this.audio.pause()
 }} />
 }
Please help 
Thank you

**Comment by sumit151199** [comment]
I need to add custom loader in extendsContent= {} ,
But i have a issue how to call loading key? 
```
isPlaying ?
<Play onClickBtn={() => {
this.audio.play()
}} />
:
<Pause onClickBtn={() => {
this.audio.pause()
}} />
}
```

**Comment by lijinke666** [comment]
Maybe you want like this ?

```
extendsContent={ ({ loading, playing, audioInfo, ...someAttrs }) => (
  loading ? xx : xx
  playing ? xx : xx
)}
```

i think it's a good idea,  can you summit a PR ?

**Comment by sumit151199** [comment]
![Screenshot](https://user-images.githubusercontent.com/51209107/108496590-46b58f80-72d0-11eb-9354-8f69d0979e1a.png)
Actually i want this player UI and also loader play button.

**Comment by sumit151199** [comment]
> Hello @sumit151199, welcome your PR. or fork the project for Implement this functionality yourself
> 你好 @sumit151199，期待你的PR, 而不是要求我实现这功能, 当然你也可以自行fork本仓库自行实现。

Show error :>
![Screenshotsa](https://user-images.githubusercontent.com/51209107/108586611-a1ed8d80-7375-11eb-88d4-08a85e980ebf.png)
