### ISSUE TITLE
Player plays first track in playlist if i update playlist

### ISSUE THREAD

**Issue by SpiritMod** [lijinke666/react-music-player#325]
### Description
Player plays first track in playlist if i update playlist

### Steps to Reproduce
1) play track on page with index > 0
2) click twice on button loadmore "Больше →"

player setPlay first track with index 0

**Comment by lijinke666** [comment]
if audio list changed, current play index is reset

https://github.com/lijinke666/react-music-player/blob/d76cb6b391c4e1c2d98d46fc1264ff52f5fb6dfb/src/index.js#L2419-L2422

if you want to control current play index , i think you should use `playIndex` props. more detail see : https://github.com/lijinke666/react-music-player/issues/286
