### ISSUE TITLE
when "id" elements are present in audioList, sorting is messed up

### ISSUE THREAD

**Issue by binary1230** [lijinke666/react-music-player#328]
### Version
tested on 4.22.1 and 4.21.1

### Steps

Given input like this:
```json
 [ {
    "id": 0,
    "name": "Something",
    "musicSrc": "Something1.mp3"
  },  {
    "id": 1,
    "name": "Something else",
    "musicSrc": "whatever.mp3"
  }]
```

the key thing is: "id" is a field I'm passing in.  it comes from another part of my app and I expected it to be ignored by react-music-player. 

However, react-music-player gets confused about the first item in the playlist (with .id == 0) and reoders it at the end. I didn't realize that "id" was a field used internally. The conflict causes odd behavior like the audiolist sorting being messed up.

If I remove the "id" field, everything works as inteded.  If I leave it, everything is off by one when using playIndex. 

### Comments

I'll try and post a better repro when I have time.

It has something to do with the internal code looking up the track id:
https://github.com/lijinke666/react-music-player/blob/d76cb6b391c4e1c2d98d46fc1264ff52f5fb6dfb/src/index.js#L837

https://github.com/lijinke666/react-music-player/blob/d76cb6b391c4e1c2d98d46fc1264ff52f5fb6dfb/src/index.js#L1864
```
id: uuId(),
```

Possible solutions:
1. Filter out "id" from any audiolist data being passed in
2. Throw an error if "id" exists on audiolist data
3. Fix underlying code to not use the "id" field (maybe ```delete audio.id```)

**Comment by lijinke666** [comment]
Thank your feeback, you're right, it really shouldn't be use `id` attr, i will optimize the feature later

**Comment by binary1230** [comment]
thanks much! looks great
