### ISSUE TITLE
Cannot play added songs with appendAudio | infinite loading | volume error

### ISSUE THREAD

**Issue by FluffyDiscord** [lijinke666/react-music-player#335]
**Version**
4.22.1

**Description**
When I change the audioLists using the appendAudio func, I cannot play added songs. Sometimes volume error pops in in console `Failed to set the 'volume' property on 'HTMLMediaElement': The volume provided (10000) is outside the range [0, 1]`, sometimes there are no errors at all. Basically same behavior as in #146, but with the recent version.

**Reproduce Link**
[![Edit zealous-dubinsky-sc8t1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-dubinsky-sc8t1?fontsize=14&hidenavigation=1&theme=dark)

![image](https://user-images.githubusercontent.com/10332247/111053276-cb747300-8462-11eb-9a7e-b3feebd4ce37.png)

![image](https://user-images.githubusercontent.com/10332247/111053275-c283a180-8462-11eb-9ddc-bbe99410270d.png)

 webpack

```javascript

let player = null;
let currentTrackInfo = null;

ReactDOM.render(
    React.createElement(ReactJkMusicPlayer, {
        /**
         * @param instance {ReactJkMusicPlayerInstance}
         */
        getAudioInstance(instance){
            player = instance
        },
        /**
         * @param info {ReactJkMusicPlayerAudioInfo}
         */
        onAudioPlay(info) {
            currentTrackInfo = info
        },
        quietUpdate: true,
        remember: true,
        spaceBar: true,
        showMediaSession: true,
        mode: 'full',
        // audioLists: JSON.parse(this.root.attr('data-list')),
        // audioLists: audioLists,
    }),
    this.root.get(0),
)

```

somewhere else
```javascript

player.appendAudio(0, tracks);
```

**Comment by lijinke666** [comment]
Please use audioLists props, the `appendAudio` is a bad implementation, I'll delete it later
