### ISSUE TITLE
Multiple same songs at different playIndex and option to disable playlist sortable panel

### ISSUE THREAD

**Issue by FluffyDiscord** [lijinke666/react-music-player#336]
### Description

Let's say that I love some songs more that other ones and want to play the same song twice in the same list, but at different playIndex:

**0: song1**
1: song2
2: song3
**3: song1**

but this error pops in when I update component state

`react-dom.development.js:67 Warning: Encountered two children with the same key, 82b23f67-4dac-fa8c-9b18-7c25e4d07ab3. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

![image](https://user-images.githubusercontent.com/10332247/111201939-97fd2a00-85c3-11eb-978c-577c38b5235f.png)

Can we somehow have that option? To include one song multiple times in the playlist ? and AFAIK we can not turn off the sortable panel, only option is to hard hide with css and waste resources(?) on component updates as it redraws it.

![image](https://user-images.githubusercontent.com/10332247/111203656-92084880-85c5-11eb-9604-68bd38b99f8a.png)

**Comment by lijinke666** [comment]
About disable sortable panel

```tsx
<ReactJkMusicPlayer sortableOptions={{ disabled: true }}/>
```

> Can we somehow have that option? To include one song multiple times in the playlist ? 

same songs is supported, what is your code ?

![image](https://user-images.githubusercontent.com/21015895/111245526-bef94180-863f-11eb-90d0-841eb6ae65da.png)

**Comment by FluffyDiscord** [comment]
I am sorry to bother so much lately, thank you for the sortable tip. Here's sandbox of my issue. I am probably doing something exceptionally wrong. Basically calling the addTracks() messes up everything and I don't know why to be honest.

[![Edit gallant-cdn-lgvz3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-cdn-lgvz3?fontsize=14&hidenavigation=1&theme=dark)

**Comment by FluffyDiscord** [comment]
Hello, any luck ? I found out that this error shows when `clearPriorAudioLists` is set to `true`. If it's set to `false` songs are added, but not visible/playable.

![image](https://user-images.githubusercontent.com/10332247/111670118-c8d59d00-8817-11eb-8c4c-6f0632acbfb8.png)

**Comment by lijinke666** [comment]
I understand why need add tracks twice ？
![image](https://user-images.githubusercontent.com/21015895/112486708-183b4080-8db7-11eb-98d2-e368bf69aa4d.png)

**Comment by FluffyDiscord** [comment]
That is just an example. I have API which sends songs via js `fetch()`, then I render these songs on my page, storing the data inside these elements (jQuery .data()). Then when I want to play them, I acess that data and append them to the song list. And that is where my issue is. Adding same song twice triggers bunch of errors, just like the example. The two `setTimeout` is just simulating the process from API to the `this.addTracks()`.

I can send send you my project url via private message, where this happens, so you can see the whole implementation, if you need.

**Comment by lijinke666** [comment]
First, player add a uuid tag when init for drag or delete
https://github.com/lijinke666/react-music-player/blob/83d05e238ae6349ccc0c7c75fe2c39d5139df3e5/src/index.js#L1892
so, from your codesanbox example, i think the crux of the question is you should update your code like this, you should merge track list when api called, instead of updating it twice

```tsx
const [tracksA, tracksB] = await Promise.all([YOU_API, YOUR_API])

...

this.addTracks([...trancksA, ...trancksB])
```

**Comment by lijinke666** [comment]
see https://codesandbox.io/s/happy-euclid-sgvou?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/21015895/112780170-db06d500-907a-11eb-86db-83a1fceab21f.png)
