### ISSUE TITLE
change primary color based on material ui.

### ISSUE THREAD

**Issue by ketangupta34** [lijinke666/react-music-player#337]
I want to change the default "green" color of the player to a custom one. the info provided in the documents is not working. is there a more easy method to do so???

**Comment by lijinke666** [comment]
Why not work？you code ? why don't use issue template? why? your less-loader version is ? There is not a shred of useful information??

less loader v6

```js
  lessOptions: {
    javascriptEnabled: true,
    modifyVars: { '@primary-color': '#f63' },
  },
```

less loader v5

```
{
  javascriptEnabled: true,
  modifyVars: { '@primary-color': '#f63' },
}
```

![image](https://user-images.githubusercontent.com/21015895/112489378-59345480-8db9-11eb-9589-68bf6bc62627.png)
