### ISSUE TITLE
Bug: a new song get added at the end of audio list 

### ISSUE THREAD

**Issue by RitikPandey1** [lijinke666/react-music-player#343]
### Version
4.23.0
### Descriptionon
Updating the audio list adds a new song at the end of the queue. 
For example, I have four songs in the playlist [A, B, C, D],  B is currently playing...  
Now, if I want to add new song E in between B and C then the new audio list look something like this : [A, B, E, C, D], But in the music player playlist song E get added at the end of the queue, [A, B, C, D, E] like this. 

### Reproduce Link
https://codesandbox.io/s/react-music-player-h09eb?file=/src/App.js
### Steps to Reproduce
1. Go to the link : https://codesandbox.io/s/react-music-player-h09eb?file=/src/App.js
2. click the `add song` button
3. Open music player playlist
### Expected Behavior
It should add the new song in the third position instead of at the end
### Current Behavior
A new song added at the end

**Comment by lijinke666** [comment]
Why not use `clearPriorAudioLists` props?

![image](https://user-images.githubusercontent.com/21015895/113802172-d0d88b00-978c-11eb-9287-17f05c5aa557.png)

**Comment by lijinke666** [comment]
This code is from three years ago when I was learning React, this is a bad implementation
https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2031-L2049

In fact, playlists should be controlled by the user, like, audio order, audio lists length, The player should only receive `audioLists` props, do nothing effects, but to keep compatible, I kept the code and added a new parameter [Detail](https://github.com/lijinke666/react-music-player/pull/70)

this parameter will be removed in version 5.0. Please use this parameter for the time being

**Comment by RitikPandey1** [comment]
> Why not use `clearPriorAudioLists` props?
> 
> ![image](https://user-images.githubusercontent.com/21015895/113802172-d0d88b00-978c-11eb-9287-17f05c5aa557.png)

If I set `clearPriorAudioLists = true` then it starts the playlist from the first song, so if currently song B is playing and I update the playlist then it starts song A. I don't want to start my playlist from the beginning just want to update it

**Comment by RitikPandey1** [comment]
> This code is from three years ago when I was learning React, this is a bad implementation
> https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2031-L2049
> 
> In fact, playlists should be controlled by the user, like, audio order, audio lists length, The player should only receive `audioLists` props, do nothing effects

 Yes, If the player only receives `audioLists` prop  without adding any other effects  when `clearPriorAudioList=false`, then maybe it solves the described bug

**Comment by lijinke666** [comment]
No. any scenario in which `clearPriorAudioList=false` is used is wrong , the solution of the problem, i think you should  update your `playIndex` when audio list changed. see #286 #325
Of course, I think the best implementation is to update the playlist if there are songs that were playing before the update, the play index should not change, Instead, play index reset, if the display declares playIndex, it is preferred
