### ISSUE TITLE
如何做到淡出的效果呢

### ISSUE THREAD

**Issue by hakanaku1234** [lijinke666/react-music-player#344]
### Description
遇到的问题: 
歌曲播放到一半瞬间切歌、瞬间停止 有时会爆音

需求:
有没有类似 `onBeforeAudioPause` `onBeforeAudioPlayTrackChange` 的 api 可以做到淡出呢 (音量递减至0再停止、切歌) 

另外想请问 想修改 `mediaSession` 的 handler 但是用关键字搜不到 这部份要在哪边修改呢 
非常感谢~

### Expect Api Name
`onBeforeAudioPause` `onBeforeAudioPlayTrackChange`

**Comment by lijinke666** [comment]
meidaSession 在 这个位置
https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2233

你的需求尝试来一个pr？

**Comment by hakanaku1234** [comment]
好的好的 感谢哈! 
研究一下 我现在前端方面还是个小萌新 先努力试看看 :)

**Comment by hakanaku1234** [comment]
想请教如果想在本地开发然后于 `create-react-app` 建立的专案中引用、测试
怎么样的建置过程才是正确的呢

目前遇到的困难是

> 如果直接 `yarn add react-jinke-music-player` 引用是正常没有问题的
但是如果 `git clone` 然后 `yarn add` 这样安装再引用就会各种报错

---

详细操作过程如下:
1. git clone https://github.com/lijinke666/react-music-player.git /tmp/react-music-player
2. create-react-app /tmp/practice
3. cd /tmp/practice/
4. yarn add /tmp/react-music-player && yarn
5. vim src/App.js # 引入 ReactJkMusicPlayer 
```
import logo from "./logo.svg";
import "./App.css";
import ReactJkMusicPlayer from "react-jinke-music-player";

function App() {
    return (
        <div className="App">
            <header className="App-header">
                <ReactJkMusicPlayer />
                <img src={logo} className="App-logo" alt="logo" />
                <p>
                    Edit <code>src/App.js</code> and save to reload.
                </p>
                <a className="App-link" href="https://reactjs.org" target="_blank" rel="noopener noreferrer">
                    Learn React
                </a>
            </header>
        </div>
    );
}

export default App;
```
6. yarn start

**Comment by lijinke666** [comment]
本地开发为什么用 cra 脚手架?

直接  

```bash
git clone  https://github.com/lijinke666/react-music-player.git
cd react-music-player
yarn
yarn start
```

访问 `localhost:8084` 既可
