### ISSUE TITLE
Support lyrics without timestamps?

### ISSUE THREAD

**Issue by aldrinjenson** [lijinke666/react-music-player#346]
### Description
Hi, currently the lyrics works fine if it is given in the correct timestamped format. But crashes(no lyrics available) when the timestamps are removed. 
Is there a way to automatically show something else like a Modal/portal that displays the full lyrics text if there are no timestamps available? (getting timestamped lyrics is hard right..? any good resource you know for the same :)? )

**Comment by lijinke666** [comment]
You can use `extendsContent` customize your lyric, get current playing audio lyric by `onAudioPlayTrackChange` or `onAudioPlay`

```tsx
const showLyricModal = () => {
  const currentPlayAudioInfo = ...
  Modal.open({ content: currentPlayAudioInfo.lyric })
}
<ReactJkMusicPlayer showLyric={false} extendsContent={<button onClick={showLyricModal}>show lyric</button>} />;
```

**Comment by deluan** [comment]
Thanks for the suggestion @lijinke666 , but if I get it right, this would make the experience of timestamped lyrics different from lyrics without timestamps... I think what @aldrinjenson is asking for is a way to have a more consistent experience for the user.
