### ISSUE TITLE
Way to extend the playPrev and playNext functions

### ISSUE THREAD

**Issue by aniketbiswas21** [lijinke666/react-music-player#347]
### Description
Currently, we cannot add our logic to the default methods of playing the prev track or next track. 

https://github.com/lijinke666/react-music-player/blob/master/src/index.js#L1539-L1551

Let's say, I click on the previous button. I want to check that if the `AudioInstance` 's currentTime is greater than `0`, then restart the current track and if not, play the previous track. Is there any way to configure this?

### Expect Api Name
`onAudioPrev`/ `onAudioNext`

**Comment by lijinke666** [comment]
Try send a PR ?

**Comment by aniketbiswas21** [comment]
Sure!
