### ISSUE TITLE
Restore state of currently playing song when audioList changes. 

### ISSUE THREAD

**Issue by YashJipkate** [lijinke666/react-music-player#349]
### Description

Currently, if the `audioList` updates, then the play state of the currently playing song is lost even if the song is present in the new audioList (possibly due to [this](https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2109)?), which makes the tracks start from the beginning.

On using `playIndex` I can get to the song but I still can't play it from the time it was paused (the song starts from 0:00). Is it possible to not clear the pause and time state of the song if it is in the updated audioList? I want to start it from where it was paused. 

A possible fix could be to add a parameter to [`changeAudioLists`](https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L2107) that would use something like [`checkCurrentPlayingAudioIsInUpdatedAudioLists`](https://github.com/lijinke666/react-music-player/blob/1c7b9f732b12e4516b8f079533ded821fe81b157/src/index.js#L1743) to get the current playing song index in the new audioList and set its `currentTime` to that of the previous state (before updating of the audioList)?

Or is there some other method already present to carry this out?

**Comment by lijinke666** [comment]
you can use `quietUpdate`

see: https://github.com/lijinke666/react-music-player#bulb-quiet-update

**Comment by YashJipkate** [comment]
I am already using quietUpdate. But it only works when songs are added to the end of the queue or if the currently playing song is the first song in the queue. You can reproduce this issue by going to https://demo.navidrome.org/ and:
- Go to playlist section.
- Play a playlist and select a song from the queue not on the first position.
- Go to another playlist and click 'Play Next'.
- See the first song being played.

Here is the code of the player - https://github.com/navidrome/navidrome/blob/da30923a95a3ac9cdfc8643c690cf98792d9989a/ui/src/audioplayer/Player.js.
As you can see in the above code that we have already used `quietUpdate`.

Here is the screen recording: 

https://user-images.githubusercontent.com/34203227/115497952-3dbe4b80-a28a-11eb-9eca-79b13c8f934c.mp4

The player loses all its state, even the play/pause state. 

It would be great if you could provide some insight into this.

**Comment by YashJipkate** [comment]
@lijinke666 could you please take a look at this?

**Comment by lijinke666** [comment]
Now. I'm too busy to deal with these problems or bugs, can you want try to send a PR?

**Comment by YashJipkate** [comment]
Yeah sure, I'll see what I can do.

**Comment by joejoe0243** [comment]
i have similar problem, updating audiolist while not playing the first will reset to play first one

**Comment by sigmakey** [comment]
Hello, I just want to say that this bug breaks what I personally see as a very important feature for any music player, namely adding songs to the queue. Specifically, it's breaking the "Play Next" functionality in the Navidrome web UI, which is otherwise excellent. I'm not a developer, so I just hope that someone can find the time to take a look at this. Thanks.

**Comment by binamov** [comment]
😿 +1 on the above comment, this ruins my queuing experience.

**Comment by SteveDinn** [comment]
This issue should be re-opened. It is very annoying behaviour.

**Comment by kpcenti** [comment]
Can this be re-opened? It's a very jarring behaviour
