### ISSUE TITLE
When changing window focus, the player skips ahead if the progress bar is the active element

### ISSUE THREAD

**Issue by srichter** [lijinke666/react-music-player#352]
### Version

4.23.0

### Description

When the window containing the player loses (and sometimes when it regains) focus while playing, the player will skip ahead slightly if the progress bar was previously used to adjust the track position.

### Steps to Reproduce

1. Play audio
2. Drag the progress bar to change the position of the track
3. Tab out of the window containing the player, or give another window focus
4. The player will slightly skip ahead

### Reproduce Link

https://www.lijinke.cn/react-music-player/

### System information

macOS Firefox 87 and Chrome 90

### Comments

The issue can be "resolved" by clicking anywhere else on the page to shift the active element away from the progress bar.

**Comment by lijinke666** [comment]
I cannot reproduce on my locale env, can you give a gif ?

**Comment by srichter** [comment]
Sorry for the poor audio; had to record it with the internal microphone. You can hear the track skip forward slightly each time the tab is switched away from the player. 

https://user-images.githubusercontent.com/933620/115655112-903a4f00-a300-11eb-9db1-9dfa4ba44136.mov

**Comment by srichter** [comment]
Looks like the bot incorrectly closed this. @lijinke666, please take a look at the video I posted when you get a chance and let me know if you need more details.

**Comment by cloudre01** [comment]
Hi facing the same issue right here, music skips ahead when switching between tab after selecting the progress bar.

Reproduced using this [codesandbox template](https://codesandbox.io/s/dreamy-mcclintock-jwzid) and chrome Version 94.0.4606.81 (64-bit)
