### ISSUE TITLE
想請問如何關閉 "歌曲拖曳" 的功能

### ISSUE THREAD

**Issue by hakanaku1234** [lijinke666/react-music-player#353]
### Description
歌曲較多時，會將playlist往上/下滑選擇歌曲
但是手機容易意外觸發 `歌曲拖曳事件` (交換兩首歌的位置)
因此希望可以關閉這項功能 非常感謝!

### Expect Api Name
dragMusicInPlayList={false}

**Comment by lijinke666** [comment]
可以使用 sortableOptions 来禁用排序
```jsx
<ReactJkMusicPlayer sortableOptions={{ disabled: true }}/>
```
