### ISSUE TITLE
Player breaks when you add a new song to the playlist

### ISSUE THREAD

**Issue by ballad89** [lijinke666/react-music-player#36]
```js
  getPlayInfo = (audioLists = []) => {
    const _audioLists = audioLists.map(info => {
      return {
        ...info,
        id: uuId()
      };
    });
    const playIndex = Math.max(
      0,
      Math.min(audioLists.length, this.props.defaultPlayIndex)
    );
    const playId = this.state.playId || _audioLists[playIndex].id;
    const { name = "", cover = "", singer = "", musicSrc = "" } =
      _audioLists.find(({ id }) => id === playId) || {};
    return { name, cover, singer, musicSrc, audioLists: _audioLists, playId };
  };
```

The method above gets called every time a new track is added to an already rendered player. So that means every track in the list gets a new `uuid` everytime
So that means `playId` would refer to a `uuid` which has been overwritten, hence this `_audioLists.find(({ id }) => id === playId)` never matches.

In essence what happens is when a song is playing and you add a new song to the playlist the resulting state is always ` { name = "", cover = "", singer = "", musicSrc = "" }` which causes the player to error

**Comment by lijinke666** [comment]
Thanks your feedback 😁
please try `4.2.0` version , i'm fixed
