### ISSUE TITLE
Unnecessary duplicate keys in AudioListsPanels

### ISSUE THREAD

**Issue by d1vshar** [lijinke666/react-music-player#378]
### Description
For the AudioListsPanel, the `__PLAYER_KEY__` is generated after comparing the `musicSrc` field. Adding the same music twice in the playlist/queue results in duplicate key errors (their error message says "Warning..."), spamming the console every render.
```
Warning: Encountered two children with the same key, `43c04fc5-719f-993c-72eb-03e12d79cc25`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behaviour is unsupported and could change in a future version.
    at ul
    at div
    at div
    at AudioListsPanel (http://localhost:3000/static/js/vendors~main.chunk.js:64365:25)
    at div
    at ReactJkMusicPlayer (http://localhost:3000/static/js/vendors~main.chunk.js:65572:5)
    at MusicPlayerBar (http://localhost:3000/static/js/main.chunk.js:923:80)
    at App
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:68499:20)
```

I'm not sure if this is an intended feature (why?). But most music _apps_ do allow duplicates in playlists/queues. 

Wouldn't it be better to just generate pseudo-random keys without comparing audio list entries. Or just not generate the keys if `__PLAYER_KEY__` is already set in received `ReactJkMusicPlayerAudioListProps` object.

**Comment by d1vshar** [comment]
This only happens when the audio list is updated. 

https://codesandbox.io/s/react-music-player-issues-378-x4evq
Press the button to add the same song into the queue.

![image](https://user-images.githubusercontent.com/32746859/118325347-f8a3d700-b520-11eb-899e-b41b3f388713.png)

**Comment by lijinke666** [comment]
For you example, you set quietUpdate = true, currently, duplicate songs are not supported with `quietUpdate` mode, 
the current playlist is compared to the updated list, i must know which ones are still there after the update，so use `musicSrc` for compared, if generated new random UUID, current play status is lost.

you can solve the problem temporarily like `quietUpdate: false`, or do you have any good suggestions, welcome to exchange
