### ISSUE TITLE
Volume not sustained

### ISSUE THREAD

**Issue by joejoe0243** [lijinke666/react-music-player#379]
### Version
Latest
### Description
volume will set to 1 when update audio list

### Steps to Reproduce
In demo page

1. play default song
2. change volume
3. click "Add audio"

Volume will set to 1

Also the changed volume is strange, it is not align with the progress bar
![volume](https://user-images.githubusercontent.com/65852943/118231432-b7300f00-b4c1-11eb-8d2b-ee5bec5713a1.jpg)

**Comment by lijinke666** [comment]
> Also the changed volume is strange, it is not align with the progress bar

see https://github.com/lijinke666/react-music-player/pull/266
