### ISSUE TITLE
.progress-bar needs a background-color 

### ISSUE THREAD

**Issue by rosariogueli** [lijinke666/react-music-player#42]
When using this player in a project where you are using a different css library that contains .progress-bar background-color, the player uses it, effectively messing the lovely theme. Please explicitly add this in the player css, for example for light theme: 
```
.react-jinke-music-player-main.light-theme .progress-bar-content .progress-bar{
  background-color: white;
}
```

**Comment by lijinke666** [comment]
Hi~ Thanks for the feedback, I will optimize it.
