### ISSUE TITLE
Seek bar scatters when dragging the handle

### ISSUE THREAD

**Issue by rosariogueli** [lijinke666/react-music-player#43]
Tried this in Chrome Version 73.0.3683.103 (Official Build) (64-bit) on my iMac v10.11.6

**Comment by lijinke666** [comment]
Hi~ Please show me your code . Please be more specific. I don't understand what you are saying

**Comment by rosariogueli** [comment]
When I use the seek bar to go to a different point of the song, I click on the handle and try to move it, it starts jumping around and looks bad.

I'm sorry but I don't have the code anymore because I decided not to use the player at the end because I don't need the mobile version and also I just need a very simple sound player so I am using a simple HTML5 audio tag now with a play/pause button.

As far as I remember there is no fancy code or anything strange, I was simply using your player with a few props, all of the issues I had I have reported to you because I care about your player. If you cannot replicate this issue, please try to include Ant Design in the project and then see if you can replicate it.
 
That is the only library I was using for the UI. 

Another reason I abandoned the player is because I tried to install the source code of your player but when I run npm install it gave me an error asking me to install yarn and I didn't want to do that. 

Have a nice day / evening.

**Comment by lijinke666** [comment]
Thanks.
