### ISSUE TITLE
Close button on mobile mode is not working

### ISSUE THREAD

**Issue by rosariogueli** [lijinke666/react-music-player#44]
When resizing my browser window to trigger the mobile version of the player skin, the close button (top right-hand side) is not doing anything and keeps the whole player on top of the website which stops user navigation.

**Comment by lijinke666** [comment]
Hi~ Because i use `onTouchStart` handle mobile mode , you can use mobile device or mobile phone mode of your browser

**Comment by rosariogueli** [comment]
Hi, thank you for the info. Yes on mobile mode it worked. I might add an update so it works also on click just in case. It would be great if you could add your answer to the documentation so people know that you're using only the touch events. Cheers.

**Comment by rosariogueli** [comment]
Also, I just tried it, while on mobile the player starts on full screen, (which should be optional?, when I tap on the close button it works as mentioned above, however when I tap on the "Open" icon (the circle with the artwork of the song), it doesn't work.
