### ISSUE TITLE
Uncaught (in promise) DOMException + Restarting music on mobile 

### ISSUE THREAD

**Issue by tahaygun** [lijinke666/react-music-player#49]
**Steps to produce:** Open the demo in chrome while mobile mode open in devtools, click anywhere. 

**Result:** The music will restart and there is an error in the console `Uncaught (in promise) DOMException`

**Comment by lijinke666** [comment]
Thanks for your feedback. I will try to fix it

**Comment by lijinke666** [comment]
@tahaygun hello, i fixed the bug . Please use `react-jinke-music-player@4.3.5`

**Comment by tahaygun** [comment]
Hi @lijinke666 , that was fast :) Thanks!
