### ISSUE TITLE
Seekbar Issue 

### ISSUE THREAD

**Issue by AhsanShafique** [lijinke666/react-music-player#52]
Player seekarbar on complete not goes to end, although timer is end

Please find the reference: https://www.screencast.com/t/iDhykahw

**Comment by lijinke666** [comment]
you music only five second ? Does your music file have an online access address . i  have time to debug the issue

**Comment by AhsanShafique** [comment]
Yes, Music file is just 5 seconds, Music files dont have online access, i am sharing a video. 
the issue is in the "rc-slider-track" its not going to 100% when audio is finished. 

Here is the reference.  https://www.screencast.com/t/STV8gHHAWAc

**Comment by lijinke666** [comment]
@AhsanShafique Hi~ i fixed it :) please reinstall `react-jinke-music-player@4.3.6` try it

**Comment by AhsanShafique** [comment]
> @AhsanShafique Hi~ i'm fixed it :) please reinstall `react-jinke-music-player@4.3.6` try it

Thank you.
