### ISSUE TITLE
React player HTML append to any div

### ISSUE THREAD

**Issue by AhsanShafique** [lijinke666/react-music-player#55]
Hi,  
I am usgin React Music player, Right now player creates its html into body. is it possible that we can append player html into any sections/div rather then body. 

I've used bounds property, but its not working.
 bounds: document.getElementById('root'),

Here it the reference: 
https://www.screencast.com/t/ESDG2mZk3s7Z

Thanks in advance.

**Comment by lijinke666** [comment]
ok i'm publish a new version later .  add a option `getContainer `  support custom append root node

**Comment by AhsanShafique** [comment]
In previous version it was working fine, wherever i place  markup <ReactJkMusicPlayer  {...item.options} /> it render html on that node.

**Comment by lijinke666** [comment]
i'm sorry . i use `import { createPortal } from "react-dom";` in `4.3.7` version to append `document.body`
because It will reduce some bugs

**Comment by lijinke666** [comment]
Hi~ Please reinstall `react-jinke-music-player@4.4.0` use like this
```jsx
<ReactJkMusicPlayer  getContainer={()=> document.body}/>

// or

<ReactJkMusicPlayer  getContainer={()=> document.querySelector('.element')}/>


```

**Comment by AhsanShafique** [comment]
> Hi~ Please reinstall `react-jinke-music-player@4.4.0` use like this
> 
> ```js-jsx
> <ReactJkMusicPlayer  getContainer={()=> document.body}/>
> 
> // or
> 
> <ReactJkMusicPlayer  getContainer={()=> document.querySelector('.element')}/>
> ```

Use like this?
 <ReactJkMusicPlayer getContainer={()=> document.querySelector('.audio-wrapper')} {...item.options} />

**Comment by AhsanShafique** [comment]
Options will remains same as it is? 
<ReactJkMusicPlayer getContainer={()=> document.querySelector('.audio-wrapper')} {...item.options} />

**Comment by lijinke666** [comment]
yes no problem . cannot work ?

**Comment by AhsanShafique** [comment]
oh sorry it works, but it does not shows timers, or seekbar and player options are not working 

Reference: https://www.screencast.com/t/XqqVOzNuA

**Comment by AhsanShafique** [comment]
Let me explain the complete scenario. 
 I've two player on my view and its rendering through .map function, every player have its own options, that's why i used item.options to assign every player its own options. there is no error in audio play. audio is playaing very well, but the options like seekbar not moving on audio play.  timer not working. 

Reference : https://www.screencast.com/t/McjkwkEFs5


here is the code:
const renderMessage = (voiceMails) => {

        return voiceMails.map((item, index) => {
          
             item.options = {
                className: "audio-player",
                defaultPlayIndex: 0,
                theme: "light",                
                glassBg: false,
                defaultPosition: {},
                openText: "Open",
                closeText: "Close",
                mode: "full",
                once: true,
                autoPlay: false,
                toggleMode: false,
                showMiniModeCover: false,
                showMiniProcessBar: false,
                drag: true,
                seeked: true,
                showProgressLoadBar: false,
                showPlay: true,
                showReload: false,
                showDownload: false,
                showPlayMode: false,
                showThemeSwitch: true,
                showLyric: false,
                extendsContent: [],
                defaultVolume: 100,
                onAudioEnded(audioInfo) {
                    //console.log("audio ended", audioInfo);
                    readHandler(item.fromNumber, item.recordingSid)
                },
                onAudioSeeked(audioInfo) {
                    console.log("audio seeked", audioInfo);
                },
                audioLists: [
                    {
                        musicSrc: () => {
                            return Promise.resolve(item.recordingMp3Uri)
                        }

                    },
                ]
            };


            return (
                <div className={"col-12 col-md-12 col-lg-10  col-xl-7"} key={index}>
                    <div className="audio-wrap">                      
                        <div className="audio-ply"  id={"player-" + index}>
                            <ReactJkMusicPlayer  {...item.options} onAudioLoadError={(error)=> console.log(error)}  getContainer={()=> document.querySelector('#player-' + index)} />
                        </div>                                       
                    </div>
                </div>
            )
        })
    }

**Comment by AhsanShafique** [comment]
@lijinke666  any solution.
