### ISSUE TITLE
Unable to Change mode programatically

### ISSUE THREAD

**Issue by Aeyzaz** [lijinke666/react-music-player#60]
Hello, I am unable to change the mode

```
setOptions({
          ...options,
          mode: "full"
        })
```

I am using useState Hook and triggering on a button click

**Comment by lijinke666** [comment]
fixed.  please use `4.4.2`

there are usually no switching mode scenarios. I'm curious about your application scenarios
the player . the purpose of this player is simply to play songs : (

**Comment by Aeyzaz** [comment]
I am initially launching the player in mini mode on mobile and as soon the playlist gets updated the player it goes to full mode.

**Comment by Aeyzaz** [comment]
Can't resolve 'react-jinke-music-player' after 4.2.2
