### ISSUE TITLE
Can't resolve 'react-jinke-music-player' after 4.4.2

### ISSUE THREAD

**Issue by Aeyzaz** [lijinke666/react-music-player#61]
4.4.1 works fine with everything working, but after 4.4.2 webpack is throwing error `Can't resolve 'react-jinke-music-player'`

**Comment by lijinke666** [comment]
@Aeyzaz hi~ i'm sorry . miss `lib` dir when i publish `4.4.2`. now. i republish new fix version `4.4.3` . thank you feedback : )

**Comment by Aeyzaz** [comment]
It works in the start but while music is playing it doesnt change the mode programatically

**Comment by Aeyzaz** [comment]
Thanks!
