### ISSUE TITLE
onAudioDownload: modify object BEFORE running core code

### ISSUE THREAD

**Issue by houmark** [lijinke666/react-music-player#67]
The `onAudioDownload` function is not very useful as it is called AFTER the redirect. The function could be useful for modifying the audio URL, for example appending `download=1`, or opening the download in a new window. To do this, the function should call the user function (if exists) first and then use the modified object to run the core code.

I hope this makes sense. And maybe this cannot be modified now due to backwards compatibility / functionality change, but then maybe a new function called something like `onBeforeAudioDownload` could be introduced to do this behavior.

Right now, clicking the download button will open the audio file in the same tab and thus killing the player and the entire React UI, and then my Chrome shows the mp3 in it's built-in player. With this function I could open in a new tab and append to the URL so that the platform that holds the mp3 will ask Chrome to download the mp3 file.

**Comment by lijinke666** [comment]
hi~ download should not open a new tab under normal circumstances .  this is a bug maybe. i need time to try fix it. thanks your feedback

**Comment by lijinke666** [comment]
open a new tab when trigger download,  because chrome not allow download cross origin assets :(

https://stackoverflow.com/questions/28318017/html5-download-attribute-not-working-when-downloading-from-another-server-even

**Comment by lijinke666** [comment]
What do you mean? Are your want use `onBeforeAudioDownload ` return a `boolean`, if return true . trigger download. if return false. not trigger download.Is that what you mean ?

**Comment by houmark** [comment]
No, I want to be able to modify the musicSrc string or the entire object in any way needed. This way  I can change the download URL on the fly BEFORE the browser opens the URL. In my case, to download the song, I need to append ?download=true to the URL of the song.

**Comment by lijinke666** [comment]
oh i understand eg.
current music src is `http://xxx.mp3` , but you need changed the music src when download

**Comment by houmark** [comment]
yes, to play: https://source.mp3
to download: https://source.mp3?download=true (but URL could be anything else which is why I would like to be able to modify anything in the object).

Making this a hook function that can read and modify the object and return it back to the core player, will solve any use case anyone may have related to downloads.

**Comment by lijinke666** [comment]
update `v4.6.0`

```tsx
const onBeforeAudioDownload =()=>  {
    return Promise.resolve({
      src: 'https://source.mp3?download=true',
    })
  }
<ReactJkMusicPlayer  onBeforeAudioDownload={onBeforeAudioDownload}/>
```

also. support transform filename and mimeType, it's optional

```tsx
const onBeforeAudioDownload =()=>  {
    return Promise.resolve({
      src: 'https://source.mp3?download=true',
      filename: 'test.mp3',
    })
  }
<ReactJkMusicPlayer  onBeforeAudioDownload={onBeforeAudioDownload}/>
```

**Comment by houmark** [comment]
Thank you! This works great!
