### ISSUE TITLE
Optional button inside player UI to fully close/kill/destroy player

### ISSUE THREAD

**Issue by houmark** [lijinke666/react-music-player#68]
While I appreciate the mini player and full player swap and plan to actively use that feature, I think a proper close function would be nice. This could be an optional button, hidden by default if you like and be an "X" type icon all the way to the right, and an "X" in the corner of the mini player.

This would simply kill the component or do a callback to a function passed in as a prop to the player.

I know you have responded to this before, and that it's possible to simply not render the player from my own code, but that does not make it easy for me to let the user show and actively close the player. Once it's floating in one way or the other, I cannot let the user close the player from within the player, unless I do a hack with a floating close button, but that really is not optimal and having it inside the player, would be much better for usability.

I was thinking that clicking the button could be a flexible prop that defaults to destroying itself, but a function could also be passed which could be a prop passed function so I can kill it from my calling component. Hope it makes sense...

**Comment by houmark** [comment]
On a related note; I have attempted to `ref` the player in my component using various techniques, but I was somewhat unsuccessful. I could get the initial state, but was unable to keep track of updates to the player component/node such as if the player was active playing music or not, full or mini player etc. This could have helped me improve the close hack, but it would never become the same as a baked-in close button/feature anyways.

**Comment by lijinke666** [comment]
done.

see https://github.com/lijinke666/react-music-player#destory-player
