### ISSUE TITLE
Make it possible to hide cover photo/image

### ISSUE THREAD

**Issue by houmark** [lijinke666/react-music-player#69]
Our recordings do not have a cover photo and the only fairly sensible cover photo to show is a logo. Currently, when no cover is available, the player renders and empty round spot. But the cover photo (all the way to the left in the full player) also takes space in the UI, so it would be nice to either;

1) Auto-hide the cover photo if no cover photo is available
2) Make it possible to configure if it's shown or not, which would allow us to add a logo image and have it shown in the mini-player while hiding it in the full player to gain UI space

NB: This will be more feature request for now. And yes, I do anticipate to try doing one or more of these myself as a PR if time permits. Mostly registering them here to hopefully get your interest into getting these features in.

**Comment by lijinke666** [comment]
update `v4.5.0`

```tsx
<ReactJkMusicPlayer autoHiddenCover />
```

**Comment by houmark** [comment]
A small snag, it seems that when there's no cover it's still rendering the placeholder and thus it will take space on the left of the player/title. Would it be possible to not render that part so we get the extra space when no cover?
