### ISSUE TITLE
Can we create peaks for the player

### ISSUE THREAD

**Issue by ganeshzehntech** [lijinke666/react-music-player#71]
Please go to https://www.npmjs.com/package/@dschoon/react-waves

If you can see the waves or peaks shows with the player, how we can do that in "react-jinke-music-player".
Please reply as soon as please.
Thank you :)

**Comment by lijinke666** [comment]
I don't understand what you mean. The player doesn't seem to have anything to do with the audio waveform, like react-waves

```js
 const props = {
  ...otherProps,
  extendsContent: [some ui button, open wave modal when clicked]
  onAudioPlayTrackChange(currentPlayId, currentAudio, audioInfo) {
    
  }
}

<ReactJkMusicPlayer {...props}/>
```
your can use  `extendsContent` add some ui or add any wrapper  to show waves

```js
<ReactWaves audioFile={audioLists[0].musicSrc}
```

then 
your can use  `currentPlayId` or  `currentAudio` to change your `react-waves` need music FIle 

```js
<ReactWaves audioFile={currentAudio.musicSrc}
```
