### ISSUE TITLE
How to play/pause song ?

### ISSUE THREAD

**Issue by thedogcampaign** [lijinke666/react-music-player#72]
Hi,

In my code
`<ReactJkMusicPlayer ref={this.player} {...params} />`

then i can use this.player.playxx()/pause this way. How to do that ? Thank you !

**Comment by lijinke666** [comment]
Hi ~
please use `getAudioInstance` api

```jsx
<ReactJkMusicPlayer 
    getAudioInstance = { instance => this.player = instance }
    }
  />

 ...

this.player.play()
this.player.pause()
```
