### ISSUE TITLE
AudioInfo has ID field ?

### ISSUE THREAD

**Issue by thedogcampaign** [lijinke666/react-music-player#73]
Let me show you my intent:
I add a song named "ABC" with ID: 123 to audioLists. Then when I pause that song in music player, the state song with same ID will change to paused as well

  //audio pause handle
```javascript
  onAudioPause(audioInfo) {
       const currenSong = findSong(audioInfo.ID)
       currentSong.playing = false
       setCurrentSong(currentSong)
  },
```
How to do that ? Thank you ! I can find the corresponding song by name but I am assuming there are same name songs

**Comment by lijinke666** [comment]
hi~ I plan tomorrow release a new version with custom fields in audioInfo

**Comment by thedogcampaign** [comment]
> 
> 
> hi~ I plan tomorrow release a new version with custom fields in audioInfo
Awesome. I am looking forward it :)

**Comment by lijinke666** [comment]
`AudioInfo` contains the custom field for audio lists now, upgrade version `4.6.1`

```jsx
function onAudioPause(audioInfo) {
  console.log(audioInfo.id) // 1
  console.log(audioInfo.test) // 2
}
<ReactJkMusicPlayer audioLists={[{id:1, test: 2, ...}]}  onAudioPause={onAudioPlay}/>
```
