### ISSUE TITLE
最新master分支的代码,自动播放无效,要刷新一次才能

### ISSUE THREAD

**Issue by patience00** [lijinke666/react-music-player#78]
### Steps

```js
/**
 * code
 */


```

**Comment by lijinke666** [comment]
我这边本地不能复现, 请提供一个能稳定复现的 在线链接

**Comment by vl-ad** [comment]
Also have the same problem. When you pass "autoPlay: false" after that you should click the "Play" button twice to launch the player. 
It easy reproduce even on demo on master. Just pass "autoPlay: false" in the paramerts and you will see it.

Problem is in loadAndPlayAudio method and canPlay variable.

**Comment by lijinke666** [comment]
@vl-ad ok 👍

**Comment by lijinke666** [comment]
fixed.
