### ISSUE TITLE
Play/Pause from custom Button doesn't sync with the player button

### ISSUE THREAD

**Issue by NISHANT061** [lijinke666/react-music-player#79]
Trying to control play and pause with custom buttons doesn't work .Issue is the audio gets paused/played if i do this.audio.pause()/this.audio.play() . But the play/pause button doesn't sync with audio play/pause.

this.state = {
      audio:null,
      options: {
        audioLists: [
          {
            singer: "Jay Chou",
            cover: this.props.thumbnail,
            musicSrc: this.props.streamUrl,
          },
        ],
        autoPlay: true,
        mode: "full",
        clearPriorAudioLists: true,
      },
      defaultPosition: {
        bottom: 0,
      },
    };
togglePlay =()=>{
this.state.audio.pause()
}
    <ReactJkMusicPlayer {...options}  getAuioInstance={(instance=>this.setState({audio:instance})}/>
<button onClick={()=>this.togglePlay}>play</button>

**Comment by lijinke666** [comment]
The player does not support this feature. I would consider adding the feature for custom button.
In fact, if custom button is fully supported, it can cause more problems.

**Comment by lijinke666** [comment]
The reason for adding `getAuioInstance` this is because like change `playbackRate` attr, nothing to do with the player native ui, so I support pause and play from custom button later

**Comment by lijinke666** [comment]
fixed. please use `4.7.2`, thank your feedback.
