### ISSUE TITLE
Gapless playback

### ISSUE THREAD

**Issue by deluan** [lijinke666/react-music-player#81]
### Description
Are you planning to support Gapless playback? I'm planning to add this player to my music server and this would be great for playing live albums!

By the way: Thanks for this awesome player!

**Comment by lijinke666** [comment]
hi ~ @deluan  What is Gapless playback?

**Comment by deluan** [comment]
Playing tracks without any interruption (gaps) between them. This way for example you can listen to a live album without any small breaks between songs, like in the old vinyl days. 

Most digital music players today strive to provide Gapless Playback, but not everyone get it done properly.

https://en.wikipedia.org/wiki/Gapless_playback

**Comment by lijinke666** [comment]
That sounds cool, but beyond the scope of the project, you can fork the project to add new feature

have fun.

**Comment by ElleshaHackett** [comment]
I would love to see gapless playing in this player as well. I think it would be a great feature.

**Comment by certuna** [comment]
Yes, another request for gapless here - not just for live albums, but also DJ mixes, classical music, ambient, prog rock, etc - any album that is a continous piece of music subdivided into tracks.

**Comment by andrewzah** [comment]
:+1:  yet another request for this as well.

**Comment by materally** [comment]
One more request!

**Comment by certuna** [comment]
It can be done - reiterating the request: https://developers.google.com/web/fundamentals/media/mse/seamless-playback

**Comment by guim31** [comment]
+1 for gapeless playback ! Though I'm not a developer ...

**Comment by andrewzah** [comment]
The google link above is broken- here is an archived version: https://web.archive.org/web/20200414022412if_/https://developers.google.com/web/fundamentals/media/mse/seamless-playback

**Comment by ScrumpyJack** [comment]
Gapless playback is particularly welcome when listening to opera.

**Comment by bbsixzz** [comment]
Please add gapless playback, thank you.

**Comment by csrednicki** [comment]
+1

**Comment by K4r0qtuYNE5G4qgZ** [comment]
+1 for gapless playback, it's especially useful for those continues mixes that were split up.

**Comment by benoitblancquaert** [comment]
Another one!

Enjoying mixed albums is difficult with the current playback.

**Comment by VlaK0r** [comment]
I fully support it!

**Comment by bboynton97** [comment]
chiming in 5 years later that people still want gapless playback :)
