### ISSUE TITLE
历史版本的依赖包用不了了吗

### ISSUE THREAD

**Issue by patience00** [lijinke666/react-music-player#82]
### Version
4.7.1
### Description
我一直用的4.7.1，然后今天更新了前端代码（关于播放器的代码一点没动过），发布到服务器之后，发现拖拽失效了，播放器的圆圈一直跟着鼠标走，我版本没变过，是怎么回事呢
### Steps

```js
/**
 * code
 */


```

**Comment by patience00** [comment]
我用npm重新install是下载的最新版的播放器代码还是4.7.1的呢，谢谢大佬

**Comment by lijinke666** [comment]
1. 先看你是否有 package-lock.json 或者 yarn.lock 之类的锁文件
2. 其次如果 `package.json` 版本是 `~4.7.1` 还是 `^4.7.1` 如果是前者的话会下载最新的, 可以尝试将 版本改成 `4.7.1` , 然后移除 `node_modules` 然后重新安装试试

**Comment by patience00** [comment]
解决了，多谢大佬
