### ISSUE TITLE
Mute button doesn't work like unmute 

### ISSUE THREAD

**Issue by vl-ad** [lijinke666/react-music-player#84]
### Description
Mute button works only once and doesn't unmute the track.
When the track starts playing and I click "mute" button everything works well and the sound fades. But when I click this button in second time and want to unmute the track - it doesn't work.
I propose to add "toggle" functionality to the mute button, like it works, for example, on YouTube (that one click mute the video/audio and second unmute it).

**Comment by lijinke666** [comment]
ok, i'm will optimize it

**Comment by lijinke666** [comment]
fixed.
