### ISSUE TITLE
Can we change the progress-bar Interval from 1000ms to 200ms?

### ISSUE THREAD

**Issue by Irfan-clustox** [lijinke666/react-music-player#85]
Currently progress-bar update after 1000ms and i want to update progress-bar after 200ms, so that progress-bar run as a smooth way.

**Comment by lijinke666** [comment]
Sorry, not support.

the player use `timeupdate` api to update progress bar , default 1000ms.
if want set to 200ms, maybe use `setInterval` to mock.

**Comment by Irfan-clustox** [comment]
We are using this to play small audio files and recordings. It is very important to have a smooth progress bar for small duration. Can you please guide in bit detail where to add the setInterval to mock this.

Thank you for your assistance and help.
