### ISSUE TITLE
call a function when playlist is finished ?

### ISSUE THREAD

**Issue by alainib** [lijinke666/react-music-player#86]
hello

First of all thank's for this amazing package. very usefull
I made a music player connected to my NAS.
I have a express.js node API running who send the path of 10 randoms music to the frontend and i play them. 

1) when last item of the playlist is finished to call API again and get new musics

2) how to get current index played ? i can check if last item , call my API and replace playlist

I don't found a function who do that .

Any tips ?? 
thanks

**Comment by lijinke666** [comment]
Pease upgrade `4.10.0`, i enhance the `onAudioEnded` hook

the player auto add a `id` for every song,  not use playIndex, the id is added for better drag or removal between songs

if your play mode one of 'order' , 'orderLoop'

```jsx
// your audio list
const audioLists = [{ musicSrc : 'xxx'}]
```

```jsx
function onAudioEnded(currentPlayId, audioLists, audioInfo){

 // audioLists 
 // [{ musicSrc : 'xxx', id: 'xxx'}]

 if(currentPlayId === audioLists[audioLists.length - 1].id) {
  // do something...
 }
}

<ReactJkMusicPlayer audioLists={audioLists} onAudioEnded={onAudioEnded}/>
```

I hope I can help you

**Comment by alainib** [comment]
yes this work perfectly thanks
