### ISSUE TITLE
Next audio does not play if the current audio playback fails

### ISSUE THREAD

**Issue by vl-ad** [lijinke666/react-music-player#88]
### Version
4.10.0
### Description
If the current track failed to play (for example: "Uncaught (in promise) DOMException: Failed to load because no supported source was found") the next track in the playlist does not play even if "loadAudioErrorPlayNext" prop is true. But the "onAudioLoadError" callback was called. 
If try to click the "Play" button after the loading was failed  - there will be an infinite loader.
A corrupt music file which can be played is attached to below.

[Taylor Swift - Bad Blood ft. Kendrick Lamar.mp3.zip](https://github.com/lijinke666/react-music-player/files/4276229/Taylor.Swift.-.Bad.Blood.ft.Kendrick.Lamar.mp3.zip)

### Browser
Chrome 80, Windows/MacOS

**Comment by lijinke666** [comment]
hi~ thank your feedback, I'll look at it when I'm free，I've been busy lately

**Comment by lijinke666** [comment]
fixed. please try use `4.10.1`
