### ISSUE TITLE
Mini player throws error if showDestroy is false

### ISSUE THREAD

**Issue by deluan** [lijinke666/react-music-player#91]
### Version
4.10.0

### Description
When I have a MiniPlayer and the `showDestroy` option is false, if I click on the MiniPlayer, if throws an exception in the console.

### Steps to Reproduce
1) Go to the demo page (http://www.lijinke.cn/react-music-player/)
2) Disable `showDestroy` option
3) Click on the MiniPlayer

### Expected Behavior
The MiniPlayer turns into the full player version (as when the `showDestroy` option is true)

### Current Behavior
An exception is thrown in the console
```
Uncaught TypeError: Cannot read property 'contains' of null
    at Object.value [as onStop] (main.b767a6fe.js:27)
    at Object.n.onDragStop [as onStop] (main.b767a6fe.js:33)
    at HTMLDocument.o.handleDragStop (main.b767a6fe.js:33)
```

### System information
MacOS 10.14.6
Browsers tested: 
- Chrome 80.0.3987.122 (Official Build) (64-bit)
- Firefox 73.0.1 (64-bit)

### Comments
Thanks for all the hard work to make this awesome player

**Comment by lijinke666** [comment]
Fixed!  thank your feedback. there is another bug and other fixes to be released together

**Comment by lijinke666** [comment]
fixed. please try use `4.10.1`
