### ISSUE TITLE
Document how to override classes and styles

### ISSUE THREAD

**Issue by deluan** [lijinke666/react-music-player#94]
### Description

Is it possible to create an example on how to override classes and styles in the player? Ex: how to change color of buttons? 

Thanks!

**Comment by lijinke666** [comment]
```js
import ReactJkMusicPlayer from "react-jinke-music-player";
import "react-jinke-music-player/assets/index.css";
import "your/path/override.css"
```

you can find target class name to override
```css
// override.css

.react-jinke-music-player-main {
    .some-class-name {/* */}
}
```

**Comment by deluan** [comment]
Thanks for the quick reply.

Sorry, I didn't make myself totally clear: My situation is that I want to change colors as part of a theme in my application. I'd need to change this at runtime, with JS code, and not a static CSS file.

You can see what I mean from this screen capture:
![Kapture 2020-04-08 at 9 35 35](https://user-images.githubusercontent.com/331353/78790568-b8b50c80-797c-11ea-99bd-0bb42d7d550a.gif)

The idea is that new themes can be added dynamically, and themes are just a JSON file, even created by the user. If I use a CSS file, I'd need to rebuild the app to use it...

Any ideas?

**Comment by lijinke666** [comment]
Sorry. not support the feature. It's beyond the scope of the player.
but, I think you can provide some fields for your JSON schema, eg.

```
  "player":{
       "theme":"light",
       // add here extra attributes to override colors <---------
       "backgroundColor": 'red',
       "buttonColor": '#555'
   }
```
then dynamic create a `style` tag append to `<head>` tag, like this

```js
const backgroundColor =  'red'  // from parse result
const buttonColor = '#555'
const style = document.createElement('style')

// override some class name
style.innerHTML = `
    .player-target-class-name {
        background-color: ${backgroundColor}
   }
   .player-button-class-name {
       color: ${buttonColor}
   }
`

document.head.appendChild(style)
```

What do you think?

(Just found out that you and I are the same company :) )

**Comment by deluan** [comment]
Thanks for the suggestion, I will try this.

> (Just found out that you and I are the same company :) )
What a coincidence! :D
