### ISSUE TITLE
Project build failed after adding react-jinke-music-player

### ISSUE THREAD

**Issue by rahuljain-tt** [lijinke666/react-music-player#97]
### Version 
4.11.2
### Description
I am getting below error in .rc-slider which is being used by this library. 

![music-player](https://user-images.githubusercontent.com/38416798/80130517-554eef80-85b6-11ea-98b8-88e1195ba501.png)

### Steps
I am using below css loader.
```js
/**
 * MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader',
              options: {
                modules: true,
                localIdentName: '[local]'
              }
            },
            'sass-loader',
 */


```

**Comment by lijinke666** [comment]
I think this is your webpack config file problem, It has nothing to do with this player
please search by google to resolve it

Maybe try to exclude ?

```
{
      test: /\.css$/,  
      exclude: /node_modules/,  
 }
```

**Comment by baj84** [comment]
I'm having the same issue, using razzle for SSR - did you find a solution?

**Comment by baj84** [comment]
If you take a look at the webpack config for rc-slider, you'll see that it doesn't have a rule to compile CSS yet it imports a css file. The build script compiles the dist via webpack, so my guess is the problem stems from there.
